/**
 * Lessons 1-50 from .cursor/500_LESSONS.md.
 */
const SCHEMA_DDL = `CREATE TABLE wydarzenia (
  id INTEGER PRIMARY KEY,
  nazwa TEXT NOT NULL,
  data_wydarzenia DATE,
  miejsce TEXT,
  uczestnicy INTEGER
);`;

const SEED_SQL = `INSERT INTO wydarzenia (id, nazwa, data_wydarzenia, miejsce, uczestnicy) VALUES
(1, 'Dożynki', '2025-09-14', 'Park miejski', 100),
(2, 'Spotkanie cechu', '2025-10-01', 'Dom parafialny', 50),
(3, 'Kiermasz świąteczny', '2025-12-07', 'Rynek', 200),
(4, 'Koncert', '2025-10-15', 'Rynek', 80),
(5, 'Jarmark', '2025-11-20', NULL, 120),
(6, 'Wieczór poezji', '2025-09-05', NULL, 30),
(7, 'Kiermasz jesienny', '2024-10-10', 'Rynek', 90);`;

export const ZADANIA = [
  {
    id: "podstawy-select",
    theme: "polonia",
    title: "Wszystkie wydarzenia",
    goal: "Pokaż wszystkie wiersze z tabeli wydarzenia (SELECT *).",
    concept: "SELECT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 5, nazwa: "Jarmark", data_wydarzenia: "2025-11-20", miejsce: null, uczestnicy: 120 },
      { id: 6, nazwa: "Wieczór poezji", data_wydarzenia: "2025-09-05", miejsce: null, uczestnicy: 30 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia",
    version: 1,
  },
  {
    id: "where-miejsce",
    theme: "polonia",
    title: "Wydarzenia w jednym miejscu",
    goal: "Pokaż tylko wydarzenia, których miejsce to 'Rynek' (WHERE).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce = 'Rynek'",
    version: 1,
  },
  {
    id: "order-by-data",
    theme: "polonia",
    title: "Wydarzenia od najbliższego",
    goal: "Pokaż wszystkie wydarzenia posortowane po dacie rosnąco (ORDER BY).",
    concept: "ORDER BY",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
      { id: 6, nazwa: "Wieczór poezji", data_wydarzenia: "2025-09-05", miejsce: null, uczestnicy: 30 },
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 5, nazwa: "Jarmark", data_wydarzenia: "2025-11-20", miejsce: null, uczestnicy: 120 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
    ],
    solution_sql: "SELECT * FROM wydarzenia ORDER BY data_wydarzenia ASC",
    version: 1,
  },
  {
    id: "select-kolumny",
    theme: "polonia",
    title: "Tylko nazwa i data",
    goal: "Pokaż tylko kolumny nazwa i data_wydarzenia (wybór kolumn).",
    concept: "SELECT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", data_wydarzenia: "2025-09-14" },
      { nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01" },
      { nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07" },
      { nazwa: "Koncert", data_wydarzenia: "2025-10-15" },
      { nazwa: "Jarmark", data_wydarzenia: "2025-11-20" },
      { nazwa: "Wieczór poezji", data_wydarzenia: "2025-09-05" },
      { nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10" },
    ],
    solution_sql: "SELECT nazwa, data_wydarzenia FROM wydarzenia",
    version: 1,
  },
  {
    id: "select-literaly",
    theme: "polonia",
    title: "Stałe w zapytaniu",
    goal: "Pokaż nazwę wydarzenia i stały tekst 'Polonia' jako kolumnę (literały).",
    concept: "SELECT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", kolumna: "Polonia" },
      { nazwa: "Spotkanie cechu", kolumna: "Polonia" },
      { nazwa: "Kiermasz świąteczny", kolumna: "Polonia" },
      { nazwa: "Koncert", kolumna: "Polonia" },
      { nazwa: "Jarmark", kolumna: "Polonia" },
      { nazwa: "Wieczór poezji", kolumna: "Polonia" },
      { nazwa: "Kiermasz jesienny", kolumna: "Polonia" },
    ],
    solution_sql: "SELECT nazwa, 'Polonia' AS kolumna FROM wydarzenia",
    version: 1,
  },
  {
    id: "where-rowne",
    theme: "polonia",
    title: "Wydarzenie po id",
    goal: "Pokaż jeden wiersz: wydarzenie o id = 2 (WHERE z =).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE id = 2",
    version: 1,
  },
  {
    id: "where-rozne",
    theme: "polonia",
    title: "Wszystkie oprócz jednego miejsca",
    goal: "Pokaż wydarzenia, których miejsce jest różne od 'Park miejski'.",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce <> 'Park miejski'",
    version: 1,
  },
  {
    id: "where-wieksze",
    theme: "polonia",
    title: "Wydarzenia po dacie",
    goal: "Pokaż wydarzenia z datą po 2025-09-30 (WHERE z > lub >=).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 5, nazwa: "Jarmark", data_wydarzenia: "2025-11-20", miejsce: null, uczestnicy: 120 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE data_wydarzenia > '2025-09-30'",
    version: 1,
  },
  {
    id: "where-and",
    theme: "polonia",
    title: "Miejsce i data",
    goal: "Pokaż wydarzenia na Rynku i z datą przed 2025-12-01 (AND).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce = 'Rynek' AND data_wydarzenia < '2025-12-01'",
    version: 1,
  },
  {
    id: "where-or",
    theme: "polonia",
    title: "Rynek lub Park",
    goal: "Pokaż wydarzenia, których miejsce to 'Rynek' LUB 'Park miejski' (OR).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce = 'Rynek' OR miejsce = 'Park miejski'",
    version: 1,
  },
  {
    id: "where-in",
    theme: "polonia",
    title: "Miejsca z listy",
    goal: "Pokaż wydarzenia, których miejsce jest w liście: Rynek, Dom parafialny (IN).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce IN ('Rynek', 'Dom parafialny')",
    version: 1,
  },
  {
    id: "where-like",
    theme: "polonia",
    title: "Nazwy zawierające",
    goal: "Pokaż wydarzenia, których nazwa zawiera 'cech' (LIKE).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE nazwa LIKE '%cech%'",
    version: 1,
  },
  {
    id: "where-like-pct",
    theme: "polonia",
    title: "Nazwy zaczynające się",
    goal: "Pokaż wydarzenia, których nazwa zaczyna się od 'Kiermasz' (LIKE '...%').",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE nazwa LIKE 'Kiermasz%'",
    version: 1,
  },
  {
    id: "where-null",
    theme: "polonia",
    title: "Bez podanego miejsca",
    goal: "Pokaż wydarzenia, gdzie miejsce jest NULL (IS NULL).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 5, nazwa: "Jarmark", data_wydarzenia: "2025-11-20", miejsce: null, uczestnicy: 120 },
      { id: 6, nazwa: "Wieczór poezji", data_wydarzenia: "2025-09-05", miejsce: null, uczestnicy: 30 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce IS NULL",
    version: 1,
  },
  {
    id: "where-not-null",
    theme: "polonia",
    title: "Z podanym miejscem",
    goal: "Pokaż wydarzenia, gdzie miejsce nie jest NULL (IS NOT NULL).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce IS NOT NULL",
    version: 1,
  },
  {
    id: "order-by-desc",
    theme: "polonia",
    title: "Od najpóźniejszego",
    goal: "Pokaż wszystkie wydarzenia posortowane po dacie malejąco (DESC).",
    concept: "ORDER BY",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 5, nazwa: "Jarmark", data_wydarzenia: "2025-11-20", miejsce: null, uczestnicy: 120 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 6, nazwa: "Wieczór poezji", data_wydarzenia: "2025-09-05", miejsce: null, uczestnicy: 30 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
    ],
    solution_sql: "SELECT * FROM wydarzenia ORDER BY data_wydarzenia DESC",
    version: 1,
  },
  {
    id: "order-by-dwa",
    theme: "polonia",
    title: "Miejsce, potem data",
    goal: "Posortuj po miejscu, potem po dacie rosnąco (wiele kolumn w ORDER BY).",
    concept: "ORDER BY",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
      { id: 5, nazwa: "Jarmark", data_wydarzenia: "2025-11-20", miejsce: null, uczestnicy: 120 },
      { id: 6, nazwa: "Wieczór poezji", data_wydarzenia: "2025-09-05", miejsce: null, uczestnicy: 30 },
    ],
    solution_sql: "SELECT * FROM wydarzenia ORDER BY miejsce, data_wydarzenia ASC",
    version: 1,
  },
  {
    id: "order-by-where",
    theme: "polonia",
    title: "Filtr i sortowanie",
    goal: "Pokaż tylko wydarzenia na Rynku, posortowane po dacie.",
    concept: "ORDER BY",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 7, nazwa: "Kiermasz jesienny", data_wydarzenia: "2024-10-10", miejsce: "Rynek", uczestnicy: 90 },
      { id: 4, nazwa: "Koncert", data_wydarzenia: "2025-10-15", miejsce: "Rynek", uczestnicy: 80 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek", uczestnicy: 200 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce = 'Rynek' ORDER BY data_wydarzenia",
    version: 1,
  },
  {
    id: "distinct-miejsce",
    theme: "polonia",
    title: "Unikalne miejsca",
    goal: "Pokaż listę unikalnych miejsc (DISTINCT).",
    concept: "DISTINCT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny" },
      { miejsce: "Park miejski" },
      { miejsce: "Rynek" },
      { miejsce: null },
    ],
    solution_sql: "SELECT DISTINCT miejsce FROM wydarzenia",
    version: 1,
  },
  {
    id: "distinct-dwa",
    theme: "polonia",
    title: "Unikalne pary",
    goal: "Pokaż unikalne pary (nazwa, miejsce).",
    concept: "DISTINCT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", miejsce: "Park miejski" },
      { nazwa: "Spotkanie cechu", miejsce: "Dom parafialny" },
      { nazwa: "Kiermasz świąteczny", miejsce: "Rynek" },
      { nazwa: "Koncert", miejsce: "Rynek" },
      { nazwa: "Jarmark", miejsce: null },
      { nazwa: "Wieczór poezji", miejsce: null },
      { nazwa: "Kiermasz jesienny", miejsce: "Rynek" },
    ],
    solution_sql: "SELECT DISTINCT nazwa, miejsce FROM wydarzenia",
    version: 1,
  },
  {
    id: "limit-1",
    theme: "polonia",
    title: "Jeden wiersz",
    goal: "Pokaż pierwsze wydarzenie (LIMIT 1).",
    concept: "LIMIT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
    ],
    solution_sql: "SELECT * FROM wydarzenia LIMIT 1",
    version: 1,
  },
  {
    id: "limit-n",
    theme: "polonia",
    title: "Dwa wydarzenia",
    goal: "Pokaż tylko dwa pierwsze wydarzenia (LIMIT 2).",
    concept: "LIMIT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
    ],
    solution_sql: "SELECT * FROM wydarzenia LIMIT 2",
    version: 1,
  },
  {
    id: "limit-offset",
    theme: "polonia",
    title: "Drugie wydarzenie",
    goal: "Pokaż drugie wydarzenie w kolejności (LIMIT 1 OFFSET 1).",
    concept: "LIMIT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
    ],
    solution_sql: "SELECT * FROM wydarzenia LIMIT 1 OFFSET 1",
    version: 1,
  },
  {
    id: "insert-jeden",
    theme: "polonia",
    title: "Dodaj jedno wydarzenie",
    goal: "Wstaw jeden wiersz do tabeli wydarzenia (INSERT INTO ... VALUES).",
    concept: "INSERT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_insert.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "INSERT INTO wydarzenia (id, nazwa, data_wydarzenia, miejsce, uczestnicy) VALUES (8, 'Nowe wydarzenie', '2025-12-31', 'Rynek', 150)",
    version: 1,
  },
  {
    id: "insert-kolumny",
    theme: "polonia",
    title: "Wstaw z podaniem kolumn",
    goal: "Wstaw wiersz podając tylko wybrane kolumny (INSERT INTO t (col1, col2) VALUES ...).",
    concept: "INSERT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_insert.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "INSERT INTO wydarzenia (nazwa, data_wydarzenia) VALUES ('Bez miejsca', '2025-06-01')",
    version: 1,
  },
  {
    id: "insert-wiele",
    theme: "polonia",
    title: "Wstaw kilka wierszy",
    goal: "Wstaw wiele wierszy jednym INSERT (wiele VALUES).",
    concept: "INSERT",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_insert.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "INSERT INTO wydarzenia (id, nazwa, data_wydarzenia, miejsce, uczestnicy) VALUES (8, 'A', '2025-01-01', 'Rynek', 10), (9, 'B', '2025-02-01', 'Park miejski', 20)",
    version: 1,
  },
  {
    id: "update-jeden",
    theme: "polonia",
    title: "Zmień jedno pole",
    goal: "Zaktualizuj miejsce jednego wydarzenia (UPDATE ... SET ... WHERE id = ...).",
    concept: "UPDATE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "UPDATE wydarzenia SET miejsce = 'Rynek' WHERE id = 2",
    version: 1,
  },
  {
    id: "update-wiele",
    theme: "polonia",
    title: "Zmień wiele wierszy",
    goal: "Ustaw to samo pole dla wszystkich wydarzeń spełniających WHERE (UPDATE z WHERE).",
    concept: "UPDATE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "UPDATE wydarzenia SET miejsce = 'Dom parafialny' WHERE miejsce = 'Rynek'",
    version: 1,
  },
  {
    id: "update-dwa-pola",
    theme: "polonia",
    title: "Zmień dwie kolumny",
    goal: "UPDATE SET kol1 = ..., kol2 = ... WHERE ...",
    concept: "UPDATE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "UPDATE wydarzenia SET miejsce = 'Rynek', uczestnicy = 100 WHERE id = 1",
    version: 1,
  },
  {
    id: "delete-where",
    theme: "polonia",
    title: "Usuń wybrane wiersze",
    goal: "Usuń wydarzenia spełniające warunek (DELETE FROM ... WHERE ...).",
    concept: "DELETE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_delete.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "DELETE FROM wydarzenia WHERE miejsce IS NULL",
    version: 1,
  },
  {
    id: "delete-jeden",
    theme: "polonia",
    title: "Usuń jeden wiersz",
    goal: "Usuń dokładnie jeden wiersz (np. po id).",
    concept: "DELETE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_delete.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "DELETE FROM wydarzenia WHERE id = 3",
    version: 1,
  },
  {
    id: "where-not-in",
    theme: "polonia",
    title: "NOT IN",
    goal: "Pokaż wydarzenia, których miejsce NIE jest w podanej liście (NOT IN).",
    concept: "WHERE",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski", uczestnicy: 100 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny", uczestnicy: 50 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce NOT IN ('Rynek')",
    version: 1,
  },
  {
    id: "count-gwiazdka",
    theme: "polonia",
    title: "Ile wydarzeń",
    goal: "Pokaż jedną liczbę: ile jest wydarzeń (COUNT(*)).",
    concept: "Aggregates",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#count",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ "COUNT(*)": 7 }],
    solution_sql: "SELECT COUNT(*) FROM wydarzenia",
    version: 1,
  },
  {
    id: "count-kolumna",
    theme: "polonia",
    title: "Ile z miejscem",
    goal: "Pokaż liczbę wydarzeń z niepustym miejscem (COUNT(miejsce)).",
    concept: "Aggregates",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#count",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ "COUNT(miejsce)": 5 }],
    solution_sql: "SELECT COUNT(miejsce) FROM wydarzenia",
    version: 1,
  },
  {
    id: "sum-min-max",
    theme: "polonia",
    title: "Min i max daty",
    goal: "Pokaż najwcześniejszą i najpóźniejszą datę (MIN, MAX).",
    concept: "Aggregates",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ "MIN(data_wydarzenia)": "2024-10-10", "MAX(data_wydarzenia)": "2025-12-07" }],
    solution_sql: "SELECT MIN(data_wydarzenia), MAX(data_wydarzenia) FROM wydarzenia",
    version: 1,
  },
  {
    id: "avg-null",
    theme: "polonia",
    title: "Średnia",
    goal: "W tabeli z kolumną liczbową: pokaż średnią (AVG).",
    concept: "Aggregates",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#avg",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ "AVG(uczestnicy)": 95.71428571428571 }],
    solution_sql: "SELECT AVG(uczestnicy) FROM wydarzenia",
    version: 1,
  },
  {
    id: "group-by-miejsce",
    theme: "polonia",
    title: "Liczba po miejscu",
    goal: "Dla każdego miejsca pokaż liczbę wydarzeń (GROUP BY).",
    concept: "GROUP BY",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "COUNT(*)": 1 },
      { miejsce: "Park miejski", "COUNT(*)": 1 },
      { miejsce: "Rynek", "COUNT(*)": 3 },
      { miejsce: null, "COUNT(*)": 2 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*) FROM wydarzenia GROUP BY miejsce",
    version: 1,
  },
  {
    id: "group-by-dwa",
    theme: "polonia",
    title: "Grupa po dwóch kolumnach",
    goal: "Grupuj po miejscu i roku z daty; pokaż liczbę.",
    concept: "GROUP BY",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", rok: "2025", "COUNT(*)": 1 },
      { miejsce: "Park miejski", rok: "2025", "COUNT(*)": 1 },
      { miejsce: "Rynek", rok: "2024", "COUNT(*)": 1 },
      { miejsce: "Rynek", rok: "2025", "COUNT(*)": 2 },
      { miejsce: null, rok: "2025", "COUNT(*)": 2 },
    ],
    solution_sql: "SELECT miejsce, strftime('%Y', data_wydarzenia) AS rok, COUNT(*) FROM wydarzenia GROUP BY miejsce, strftime('%Y', data_wydarzenia)",
    version: 1,
  },
  {
    id: "having-count",
    theme: "polonia",
    title: "Miejsca z więcej niż jednym",
    goal: "Pokaż tylko miejsca, gdzie jest więcej niż 1 wydarzenie (HAVING COUNT(*)).",
    concept: "HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Rynek", "COUNT(*)": 3 },
      { miejsce: null, "COUNT(*)": 2 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*) FROM wydarzenia GROUP BY miejsce HAVING COUNT(*) > 1",
    version: 1,
  },
  {
    id: "having-min",
    theme: "polonia",
    title: "Grupy po warunku na agregacie",
    goal: "Filtruj grupy po MIN/MAX (HAVING).",
    concept: "HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Rynek", "MIN(data_wydarzenia)": "2024-10-10" },
    ],
    solution_sql: "SELECT miejsce, MIN(data_wydarzenia) FROM wydarzenia GROUP BY miejsce HAVING MIN(data_wydarzenia) < '2025-01-01'",
    version: 1,
  },
  {
    id: "agg-var-41",
    theme: "polonia",
    title: "SUM po grupie",
    goal: "Dla każdej grupy pokaż SUM(kolumna).",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "SUM(uczestnicy)": 50 },
      { miejsce: "Park miejski", "SUM(uczestnicy)": 100 },
      { miejsce: "Rynek", "SUM(uczestnicy)": 370 },
      { miejsce: null, "SUM(uczestnicy)": 150 },
    ],
    solution_sql: "SELECT miejsce, SUM(uczestnicy) FROM wydarzenia GROUP BY miejsce",
    version: 1,
  },
  {
    id: "agg-var-42",
    theme: "polonia",
    title: "AVG po grupie",
    goal: "Dla każdej grupy pokaż AVG(kolumna).",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "AVG(uczestnicy)": 50 },
      { miejsce: "Park miejski", "AVG(uczestnicy)": 100 },
      { miejsce: "Rynek", "AVG(uczestnicy)": 123.33333333333333 },
      { miejsce: null, "AVG(uczestnicy)": 75 },
    ],
    solution_sql: "SELECT miejsce, AVG(uczestnicy) FROM wydarzenia GROUP BY miejsce",
    version: 1,
  },
  {
    id: "agg-var-43",
    theme: "polonia",
    title: "HAVING z SUM",
    goal: "Pokaż tylko grupy gdzie SUM(...) > X.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Rynek", "SUM(uczestnicy)": 370 },
      { miejsce: null, "SUM(uczestnicy)": 150 },
    ],
    solution_sql: "SELECT miejsce, SUM(uczestnicy) FROM wydarzenia GROUP BY miejsce HAVING SUM(uczestnicy) > 100",
    version: 1,
  },
  {
    id: "agg-var-44",
    theme: "polonia",
    title: "HAVING z AVG",
    goal: "Pokaż tylko grupy gdzie AVG(...) < X.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "AVG(uczestnicy)": 50 },
      { miejsce: null, "AVG(uczestnicy)": 75 },
    ],
    solution_sql: "SELECT miejsce, AVG(uczestnicy) FROM wydarzenia GROUP BY miejsce HAVING AVG(uczestnicy) < 100",
    version: 1,
  },
  {
    id: "agg-var-45",
    theme: "polonia",
    title: "GROUP BY i ORDER BY",
    goal: "GROUP BY ... ORDER BY agregat.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Rynek", "COUNT(*)": 3 },
      { miejsce: null, "COUNT(*)": 2 },
      { miejsce: "Dom parafialny", "COUNT(*)": 1 },
      { miejsce: "Park miejski", "COUNT(*)": 1 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*) FROM wydarzenia GROUP BY miejsce ORDER BY COUNT(*) DESC",
    version: 1,
  },
  {
    id: "agg-var-46",
    theme: "polonia",
    title: "Wiele agregatów",
    goal: "SELECT grupę, COUNT(*), SUM(...), AVG(...).",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "COUNT(*)": 1, "SUM(uczestnicy)": 50, "AVG(uczestnicy)": 50 },
      { miejsce: "Park miejski", "COUNT(*)": 1, "SUM(uczestnicy)": 100, "AVG(uczestnicy)": 100 },
      { miejsce: "Rynek", "COUNT(*)": 3, "SUM(uczestnicy)": 370, "AVG(uczestnicy)": 123.33333333333333 },
      { miejsce: null, "COUNT(*)": 2, "SUM(uczestnicy)": 150, "AVG(uczestnicy)": 75 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*), SUM(uczestnicy), AVG(uczestnicy) FROM wydarzenia GROUP BY miejsce",
    version: 1,
  },
  {
    id: "agg-var-47",
    theme: "polonia",
    title: "COUNT DISTINCT",
    goal: "COUNT(DISTINCT kolumna) w grupie.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "COUNT(DISTINCT data_wydarzenia)": 1 },
      { miejsce: "Park miejski", "COUNT(DISTINCT data_wydarzenia)": 1 },
      { miejsce: "Rynek", "COUNT(DISTINCT data_wydarzenia)": 3 },
      { miejsce: null, "COUNT(DISTINCT data_wydarzenia)": 2 },
    ],
    solution_sql: "SELECT miejsce, COUNT(DISTINCT data_wydarzenia) FROM wydarzenia GROUP BY miejsce",
    version: 1,
  },
  {
    id: "agg-var-48",
    theme: "polonia",
    title: "Grupy i filtr WHERE",
    goal: "WHERE przed GROUP BY; pokaż grupy.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "COUNT(*)": 1 },
      { miejsce: "Park miejski", "COUNT(*)": 1 },
      { miejsce: "Rynek", "COUNT(*)": 3 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*) FROM wydarzenia WHERE miejsce IS NOT NULL GROUP BY miejsce",
    version: 1,
  },
  {
    id: "agg-var-49",
    theme: "polonia",
    title: "HAVING z COUNT",
    goal: "HAVING COUNT(*) = 1 (grupy jednoelementowe).",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Dom parafialny", "COUNT(*)": 1 },
      { miejsce: "Park miejski", "COUNT(*)": 1 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*) FROM wydarzenia GROUP BY miejsce HAVING COUNT(*) = 1",
    version: 1,
  },
  {
    id: "agg-var-50",
    theme: "polonia",
    title: "HAVING z dwoma warunkami",
    goal: "HAVING COUNT(*) > 1 AND SUM(...) > X.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce: "Rynek", "COUNT(*)": 3, "SUM(uczestnicy)": 370 },
    ],
    solution_sql: "SELECT miejsce, COUNT(*), SUM(uczestnicy) FROM wydarzenia GROUP BY miejsce HAVING COUNT(*) > 1 AND SUM(uczestnicy) > 200",
    version: 1,
  },
];
