/**
 * Lessons 174-223 from .cursor/500_LESSONS.md. Filled by orchestration agent.
 * Transactions (174-183), string concat (184-189), UPDATE+subquery (190-195),
 * type affinity (196-205), CREATE TABLE/INDEX/VIEW/TRIGGER (206-223).
 */
export const ZADANIA = [
  // --- 174-183: BEGIN/COMMIT/ROLLBACK/SAVEPOINT ---
  {
    id: "trans-begin-commit",
    theme: "polonia",
    title: "BEGIN i COMMIT",
    goal: "Owiń dwa INSERTy w transakcję; COMMIT.",
    concept: "BEGIN/COMMIT",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE konto (id INTEGER PRIMARY KEY, kwota INTEGER NOT NULL);`,
    seed_sql: `INSERT INTO konto (id, kwota) VALUES (1, 100), (2, 200);`,
    expected_result: [
      { id: 1, kwota: 100 },
      { id: 2, kwota: 200 },
    ],
    solution_sql: "SELECT * FROM konto ORDER BY id",
    version: 1,
  },
  {
    id: "trans-rollback",
    theme: "polonia",
    title: "ROLLBACK",
    goal: "BEGIN, INSERT, ROLLBACK; sprawdź że wiersza nie ma.",
    concept: "ROLLBACK",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE log (id INTEGER PRIMARY KEY, msg TEXT);`,
    seed_sql: ``,
    expected_result: [],
    solution_sql: "SELECT * FROM log",
    version: 1,
  },
  {
    id: "trans-savepoint",
    theme: "polonia",
    title: "SAVEPOINT",
    goal: "SAVEPOINT, zmiany, ROLLBACK TO.",
    concept: "SAVEPOINT",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_savepoint.html",
    schema_ddl: `CREATE TABLE stan (id INTEGER PRIMARY KEY, val INTEGER);`,
    seed_sql: `INSERT INTO stan (id, val) VALUES (1, 10);`,
    expected_result: [{ id: 1, val: 10 }],
    solution_sql: "SELECT * FROM stan",
    version: 1,
  },
  {
    id: "trans-release",
    theme: "polonia",
    title: "RELEASE",
    goal: "RELEASE SAVEPOINT.",
    concept: "RELEASE",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_savepoint.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, x INTEGER);`,
    seed_sql: `INSERT INTO dane (id, x) VALUES (1, 5);`,
    expected_result: [{ id: 1, x: 5 }],
    solution_sql: "SELECT * FROM dane",
    version: 1,
  },
  {
    id: "trans-implicit",
    theme: "polonia",
    title: "Transakcja domyślna",
    goal: "Kiedy SQLite zaczyna/kończy transakcję.",
    concept: "Implicit",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [],
    solution_sql: "SELECT * FROM t",
    version: 1,
  },
  {
    id: "trans-error",
    theme: "polonia",
    title: "Błąd a rollback",
    goal: "Co się dzieje przy błędzie w transakcji.",
    concept: "Error and rollback",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE test (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [],
    solution_sql: "SELECT * FROM test",
    version: 1,
  },
  {
    id: "trans-nested",
    theme: "polonia",
    title: "Zagnieżdżone savepointy",
    goal: "Wiele SAVEPOINTów i częściowy rollback.",
    concept: "Nested savepoints",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_savepoint.html",
    schema_ddl: `CREATE TABLE levels (id INTEGER PRIMARY KEY, lvl INTEGER);`,
    seed_sql: `INSERT INTO levels (id, lvl) VALUES (1, 1);`,
    expected_result: [{ id: 1, lvl: 1 }],
    solution_sql: "SELECT * FROM levels",
    version: 1,
  },
  {
    id: "trans-deferred",
    theme: "polonia",
    title: "DEFERRED",
    goal: "BEGIN DEFERRED.",
    concept: "DEFERRED",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE def (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [],
    solution_sql: "SELECT * FROM def",
    version: 1,
  },
  {
    id: "trans-immediate",
    theme: "polonia",
    title: "IMMEDIATE",
    goal: "BEGIN IMMEDIATE.",
    concept: "IMMEDIATE",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE imm (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [],
    solution_sql: "SELECT * FROM imm",
    version: 1,
  },
  {
    id: "trans-exclusive",
    theme: "polonia",
    title: "EXCLUSIVE",
    goal: "BEGIN EXCLUSIVE.",
    concept: "EXCLUSIVE",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_transaction.html",
    schema_ddl: `CREATE TABLE exc (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [],
    solution_sql: "SELECT * FROM exc",
    version: 1,
  },
  // --- 184-189: string concat ---
  {
    id: "str-concat-op",
    theme: "polonia",
    title: "Operator ||",
    goal: "Sklej nazwa i miejsce (||).",
    concept: "Operator ||",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', 'Rynek'), (2, 'Kiermasz', 'Park');`,
    expected_result: [
      { id: 1, sklejone: "Dożynki - Rynek" },
      { id: 2, sklejone: "Kiermasz - Park" },
    ],
    solution_sql: "SELECT id, nazwa || ' - ' || miejsce AS sklejone FROM wydarzenia ORDER BY id",
    version: 1,
  },
  {
    id: "str-concat-func",
    theme: "polonia",
    title: "concat()",
    goal: "Sklej stringi przez concat().",
    concept: "concat()",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_corefunc.html#concat",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', 'Rynek');`,
    expected_result: [{ id: 1, sklejone: "Dożynki | Rynek" }],
    solution_sql: "SELECT id, concat(nazwa, ' | ', miejsce) AS sklejone FROM wydarzenia",
    version: 1,
  },
  {
    id: "str-concat-ws",
    theme: "polonia",
    title: "concat_ws()",
    goal: "Sklej z separatorem (concat_ws()).",
    concept: "concat_ws()",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_corefunc.html#concat_ws",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', 'Rynek'), (2, 'Kiermasz', 'Park');`,
    expected_result: [
      { id: 1, sklejone: "Dożynki; Rynek" },
      { id: 2, sklejone: "Kiermasz; Park" },
    ],
    solution_sql: "SELECT id, concat_ws('; ', nazwa, miejsce) AS sklejone FROM wydarzenia ORDER BY id",
    version: 1,
  },
  {
    id: "str-format",
    theme: "polonia",
    title: "Format/printf",
    goal: "Sformatowany string (format/printf).",
    concept: "format()/printf()",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_corefunc.html#format",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, rok INTEGER);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, rok) VALUES (1, 'Dożynki', 2025);`,
    expected_result: [{ id: 1, opis: "Dożynki (2025)" }],
    solution_sql: "SELECT id, format('%s (%d)', nazwa, rok) AS opis FROM wydarzenia",
    version: 1,
  },
  {
    id: "str-null",
    theme: "polonia",
    title: "NULL w konkatenacji",
    goal: "Jak NULL wpływa na ||; użyj coalesce.",
    concept: "NULL w ||",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', 'Rynek'), (2, 'Kiermasz', NULL);`,
    expected_result: [
      { id: 1, sklejone: "Dożynki - Rynek" },
      { id: 2, sklejone: "Kiermasz - (brak)" },
    ],
    solution_sql: "SELECT id, nazwa || ' - ' || coalesce(miejsce, '(brak)') AS sklejone FROM wydarzenia ORDER BY id",
    version: 1,
  },
  {
    id: "str-quote",
    theme: "polonia",
    title: "quote() dla SQL",
    goal: "quote() do bezpiecznego stringa.",
    concept: "quote()",
    stopien: "uczen",
    reference: "https://www.sqlite.org/lang_corefunc.html#quote",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Dożynki'), (2, 'O''Brien');`,
    expected_result: [
      { id: 1, cytowane: "'Dożynki'" },
      { id: 2, cytowane: "'O''Brien'" },
    ],
    solution_sql: "SELECT id, quote(nazwa) AS cytowane FROM wydarzenia ORDER BY id",
    version: 1,
  },
  // --- 190-195: UPDATE + subquery ---
  {
    id: "update-subquery",
    theme: "polonia",
    title: "UPDATE z podzapytaniem",
    goal: "Ustaw kolumnę z wartości z innej tabeli (SELECT).",
    concept: "UPDATE + subquery",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: `CREATE TABLE ceny (id INTEGER PRIMARY KEY, nazwa TEXT, cena INTEGER);
CREATE TABLE rabaty (nazwa TEXT PRIMARY KEY, pct INTEGER);`,
    seed_sql: `INSERT INTO ceny (id, nazwa, cena) VALUES (1, 'A', 100), (2, 'B', 200);
INSERT INTO rabaty (nazwa, pct) VALUES ('A', 10), ('B', 20);`,
    expected_result: [
      { id: 1, nazwa: "A", cena: 90 },
      { id: 2, nazwa: "B", cena: 160 },
    ],
    solution_sql: "SELECT id, nazwa, cena - (cena * (SELECT pct FROM rabaty WHERE rabaty.nazwa = ceny.nazwa) / 100) AS cena FROM ceny ORDER BY id",
    version: 1,
  },
  {
    id: "update-from",
    theme: "polonia",
    title: "UPDATE ... FROM",
    goal: "UPDATE z JOIN (SQLite 3.33+).",
    concept: "UPDATE FROM",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: `CREATE TABLE produkty (id INTEGER PRIMARY KEY, nazwa TEXT, cena_brutto INTEGER);
CREATE TABLE vat (id INTEGER PRIMARY KEY, vat_pct INTEGER);`,
    seed_sql: `INSERT INTO produkty (id, nazwa, cena_brutto) VALUES (1, 'X', 123), (2, 'Y', 456);
INSERT INTO vat (id, vat_pct) VALUES (1, 23), (2, 8);`,
    expected_result: [
      { id: 1, nazwa: "X", cena_brutto: 123, vat_pct: 23 },
      { id: 2, nazwa: "Y", cena_brutto: 456, vat_pct: 8 },
    ],
    solution_sql: "SELECT p.id, p.nazwa, p.cena_brutto, v.vat_pct FROM produkty p JOIN vat v ON p.id = v.id ORDER BY p.id",
    version: 1,
  },
  {
    id: "update-correlated",
    theme: "polonia",
    title: "Skorelowane podzapytanie w SET",
    goal: "(SELECT ... FROM t2 WHERE t2.id = t1.id) w SET.",
    concept: "Correlated subquery",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: `CREATE TABLE t1 (id INTEGER PRIMARY KEY, val INTEGER);
CREATE TABLE t2 (id INTEGER PRIMARY KEY, bonus INTEGER);`,
    seed_sql: `INSERT INTO t1 (id, val) VALUES (1, 10), (2, 20);
INSERT INTO t2 (id, bonus) VALUES (1, 5), (2, 10);`,
    expected_result: [
      { id: 1, val: 15 },
      { id: 2, val: 30 },
    ],
    solution_sql: "SELECT id, val + (SELECT bonus FROM t2 WHERE t2.id = t1.id) AS val FROM t1 ORDER BY id",
    version: 1,
  },
  {
    id: "update-multi-row",
    theme: "polonia",
    title: "Wiele wierszy z subquery",
    goal: "Aktualizuj wiele wierszy na podstawie JOIN.",
    concept: "Multiple rows",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: `CREATE TABLE zam (id INTEGER PRIMARY KEY, klient_id INTEGER, suma INTEGER);
CREATE TABLE klienci (id INTEGER PRIMARY KEY, rabat INTEGER);`,
    seed_sql: `INSERT INTO zam (id, klient_id, suma) VALUES (1, 1, 100), (2, 2, 200);
INSERT INTO klienci (id, rabat) VALUES (1, 5), (2, 10);`,
    expected_result: [
      { id: 1, klient_id: 1, suma: 95 },
      { id: 2, klient_id: 2, suma: 180 },
    ],
    solution_sql: "SELECT z.id, z.klient_id, z.suma - (z.suma * k.rabat / 100) AS suma FROM zam z JOIN klienci k ON z.klient_id = k.id ORDER BY z.id",
    version: 1,
  },
  {
    id: "update-from-where",
    theme: "polonia",
    title: "UPDATE FROM z WHERE",
    goal: "UPDATE ... FROM ... WHERE.",
    concept: "UPDATE FROM WHERE",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: `CREATE TABLE a (id INTEGER PRIMARY KEY, x INTEGER);
CREATE TABLE b (id INTEGER PRIMARY KEY, y INTEGER);`,
    seed_sql: `INSERT INTO a (id, x) VALUES (1, 1), (2, 2);
INSERT INTO b (id, y) VALUES (1, 10), (2, 20);`,
    expected_result: [
      { id: 1, x: 10 },
      { id: 2, x: 20 },
    ],
    solution_sql: "SELECT a.id, b.y AS x FROM a JOIN b ON a.id = b.id ORDER BY a.id",
    version: 1,
  },
  {
    id: "update-join-syntax",
    theme: "polonia",
    title: "Składnia UPDATE z JOIN",
    goal: "Prawidłowa składnia UPDATE w SQLite.",
    concept: "UPDATE join syntax",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_update.html",
    schema_ddl: `CREATE TABLE główna (id INTEGER PRIMARY KEY, val INTEGER);
CREATE TABLE ref (id INTEGER PRIMARY KEY, val INTEGER);`,
    seed_sql: `INSERT INTO główna (id, val) VALUES (1, 0), (2, 0);
INSERT INTO ref (id, val) VALUES (1, 100), (2, 200);`,
    expected_result: [
      { id: 1, val: 100 },
      { id: 2, val: 200 },
    ],
    solution_sql: "SELECT g.id, r.val FROM główna g JOIN ref r ON g.id = r.id ORDER BY g.id",
    version: 1,
  },
  // --- 196-205: type affinity ---
  {
    id: "type-affinity",
    theme: "polonia",
    title: "Typ affinity",
    goal: "INTEGER, TEXT, REAL, BLOB; jak SQLite przechowuje.",
    concept: "Type affinity",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE typy (id INTEGER PRIMARY KEY, i INTEGER, t TEXT, r REAL, b BLOB);`,
    seed_sql: `INSERT INTO typy (id, i, t, r, b) VALUES (1, 42, 'tekst', 3.14, x'0102');`,
    expected_result: [
      { id: 1, i: 42, t: "tekst", r: 3.14 },
    ],
    solution_sql: "SELECT id, i, t, r FROM typy",
    version: 1,
  },
  {
    id: "type-null",
    theme: "polonia",
    title: "NULL",
    goal: "Kiedy kolumna jest NULL; IS NULL / IS NOT NULL.",
    concept: "NULL",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, a TEXT, b TEXT);`,
    seed_sql: `INSERT INTO t (id, a, b) VALUES (1, 'x', 'y'), (2, NULL, 'y'), (3, 'x', NULL);`,
    expected_result: [
      { id: 2, a: null, b: "y" },
    ],
    solution_sql: "SELECT id, a, b FROM t WHERE a IS NULL",
    version: 1,
  },
  {
    id: "type-storage",
    theme: "polonia",
    title: "Klasy przechowywania",
    goal: "integer, real, text, blob, null.",
    concept: "Storage classes",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datatype3.html",
    schema_ddl: `CREATE TABLE storage (id INTEGER PRIMARY KEY, val);`,
    seed_sql: `INSERT INTO storage (id, val) VALUES (1, 1), (2, 1.5), (3, 'x'), (4, NULL);`,
    expected_result: [
      { id: 1, typ: "integer" },
      { id: 2, typ: "real" },
      { id: 3, typ: "text" },
      { id: 4, typ: "null" },
    ],
    solution_sql: "SELECT id, typeof(val) AS typ FROM storage ORDER BY id",
    version: 1,
  },
  {
    id: "type-coercion",
    theme: "polonia",
    title: "Koercja",
    goal: "Co się dzieje przy INSERT string do INTEGER.",
    concept: "Coercion",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datatype3.html",
    schema_ddl: `CREATE TABLE coercion (id INTEGER PRIMARY KEY, col INTEGER);`,
    seed_sql: `INSERT INTO coercion (id, col) VALUES (1, '42');`,
    expected_result: [{ id: 1, col: 42, typ: "integer" }],
    solution_sql: "SELECT id, col, typeof(col) AS typ FROM coercion",
    version: 1,
  },
  {
    id: "type-typeof",
    theme: "polonia",
    title: "typeof()",
    goal: "Pokaż klasę przechowywania (typeof()).",
    concept: "typeof()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#typeof",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, v);`,
    seed_sql: `INSERT INTO t (id, v) VALUES (1, 10), (2, 'abc'), (3, 1.5);`,
    expected_result: [
      { id: 1, v: 10, typ: "integer" },
      { id: 2, v: "abc", typ: "text" },
      { id: 3, v: 1.5, typ: "real" },
    ],
    solution_sql: "SELECT id, v, typeof(v) AS typ FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "type-cast",
    theme: "polonia",
    title: "CAST",
    goal: "CAST(col AS INTEGER), CAST(col AS TEXT).",
    concept: "CAST",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_expr.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, col TEXT);`,
    seed_sql: `INSERT INTO t (id, col) VALUES (1, '123'), (2, '3.14');`,
    expected_result: [
      { id: 1, col: "123", as_int: 123 },
      { id: 2, col: "3.14", as_int: 3 },
    ],
    solution_sql: "SELECT id, col, CAST(col AS INTEGER) AS as_int FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "type-integer",
    theme: "polonia",
    title: "Typ INTEGER",
    goal: "Przechowywanie liczb całkowitych.",
    concept: "INTEGER",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datatype3.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, n INTEGER);`,
    seed_sql: `INSERT INTO t (id, n) VALUES (1, 0), (2, -1), (3, 999999);`,
    expected_result: [
      { id: 1, n: 0 },
      { id: 2, n: -1 },
      { id: 3, n: 999999 },
    ],
    solution_sql: "SELECT * FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "type-text",
    theme: "polonia",
    title: "TEXT",
    goal: "Przechowywanie tekstu.",
    concept: "TEXT",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datatype3.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, txt TEXT);`,
    seed_sql: `INSERT INTO t (id, txt) VALUES (1, 'Polonia'), (2, 'Śląsk');`,
    expected_result: [
      { id: 1, txt: "Polonia" },
      { id: 2, txt: "Śląsk" },
    ],
    solution_sql: "SELECT * FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "type-real",
    theme: "polonia",
    title: "REAL",
    goal: "Liczby zmiennoprzecinkowe.",
    concept: "REAL",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datatype3.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, r REAL);`,
    seed_sql: `INSERT INTO t (id, r) VALUES (1, 3.14), (2, -0.5);`,
    expected_result: [
      { id: 1, r: 3.14 },
      { id: 2, r: -0.5 },
    ],
    solution_sql: "SELECT * FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "type-blob",
    theme: "polonia",
    title: "BLOB",
    goal: "Dane binarne.",
    concept: "BLOB",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datatype3.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, b BLOB);`,
    seed_sql: `INSERT INTO t (id, b) VALUES (1, x'000102');`,
    expected_result: [{ id: 1 }],
    solution_sql: "SELECT id FROM t",
    version: 1,
  },
  // --- 206-223: CREATE TABLE/INDEX/VIEW ---
  {
    id: "create-table",
    theme: "polonia",
    title: "CREATE TABLE",
    goal: "Utwórz tabelę z kolumnami i typami.",
    concept: "CREATE TABLE",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT NOT NULL, data_wydarzenia DATE);`,
    seed_sql: ``,
    expected_result: [{ name: "wydarzenia", type: "table" }],
    solution_sql: "SELECT name, type FROM sqlite_master WHERE type='table' AND name='wydarzenia'",
    version: 1,
  },
  {
    id: "create-primary-key",
    theme: "polonia",
    title: "PRIMARY KEY",
    goal: "Klucz główny (pojedynczy i złożony).",
    concept: "PRIMARY KEY",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (a INTEGER, b INTEGER, PRIMARY KEY (a, b));`,
    seed_sql: `INSERT INTO t (a, b) VALUES (1, 1), (1, 2);`,
    expected_result: [
      { a: 1, b: 1 },
      { a: 1, b: 2 },
    ],
    solution_sql: "SELECT * FROM t ORDER BY a, b",
    version: 1,
  },
  {
    id: "create-unique",
    theme: "polonia",
    title: "UNIQUE",
    goal: "Ograniczenie UNIQUE.",
    concept: "UNIQUE",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, kod TEXT UNIQUE);`,
    seed_sql: `INSERT INTO t (id, kod) VALUES (1, 'A'), (2, 'B');`,
    expected_result: [
      { id: 1, kod: "A" },
      { id: 2, kod: "B" },
    ],
    solution_sql: "SELECT * FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "create-not-null",
    theme: "polonia",
    title: "NOT NULL",
    goal: "NOT NULL na kolumnach.",
    concept: "NOT NULL",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, wymagane TEXT NOT NULL);`,
    seed_sql: `INSERT INTO t (id, wymagane) VALUES (1, 'wartość');`,
    expected_result: [{ id: 1, wymagane: "wartość" }],
    solution_sql: "SELECT * FROM t",
    version: 1,
  },
  {
    id: "create-default",
    theme: "polonia",
    title: "DEFAULT",
    goal: "DEFAULT (literal, datetime('now')).",
    concept: "DEFAULT",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, x INTEGER DEFAULT 0, ts TEXT DEFAULT (datetime('now')));`,
    seed_sql: `INSERT INTO t (id) VALUES (1);`,
    expected_result: [{ id: 1, x: 0 }],
    solution_sql: "SELECT id, x FROM t",
    version: 1,
  },
  {
    id: "create-check",
    theme: "polonia",
    title: "CHECK",
    goal: "CHECK (col > 0), CHECK (col IN (...)).",
    concept: "CHECK",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, val INTEGER CHECK (val > 0));`,
    seed_sql: `INSERT INTO t (id, val) VALUES (1, 10), (2, 20);`,
    expected_result: [
      { id: 1, val: 10 },
      { id: 2, val: 20 },
    ],
    solution_sql: "SELECT * FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "create-foreign-key",
    theme: "polonia",
    title: "FOREIGN KEY",
    goal: "REFERENCES; opcjonalne ON DELETE/UPDATE.",
    concept: "FOREIGN KEY",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE rodzic (id INTEGER PRIMARY KEY);
CREATE TABLE dziecko (id INTEGER PRIMARY KEY, rodzic_id INTEGER REFERENCES rodzic(id));`,
    seed_sql: `INSERT INTO rodzic (id) VALUES (1);
INSERT INTO dziecko (id, rodzic_id) VALUES (1, 1);`,
    expected_result: [{ id: 1, rodzic_id: 1 }],
    solution_sql: "SELECT * FROM dziecko",
    version: 1,
  },
  {
    id: "create-index",
    theme: "polonia",
    title: "CREATE INDEX",
    goal: "Indeks pojedynczy i złożony.",
    concept: "CREATE INDEX",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createindex.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, a INTEGER, b INTEGER);
CREATE INDEX idx_a ON t(a);
CREATE INDEX idx_ab ON t(a, b);`,
    seed_sql: `INSERT INTO t (id, a, b) VALUES (1, 10, 1), (2, 10, 2);`,
    expected_result: [
      { name: "idx_a", type: "index" },
      { name: "idx_ab", type: "index" },
    ],
    solution_sql: "SELECT name, type FROM sqlite_master WHERE type='index' AND name LIKE 'idx_%' ORDER BY name",
    version: 1,
  },
  {
    id: "create-view",
    theme: "polonia",
    title: "CREATE VIEW",
    goal: "Widok jako zapisane SELECT.",
    concept: "CREATE VIEW",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createview.html",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);
CREATE VIEW v_rynek AS SELECT id, nazwa FROM wydarzenia WHERE miejsce = 'Rynek';`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', 'Rynek'), (2, 'Inne', 'Park');`,
    expected_result: [{ id: 1, nazwa: "Dożynki" }],
    solution_sql: "SELECT * FROM v_rynek",
    version: 1,
  },
  {
    id: "alter-table",
    theme: "polonia",
    title: "ALTER TABLE",
    goal: "ADD COLUMN (ograniczenia SQLite).",
    concept: "ALTER TABLE",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_altertable.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY);
-- ADD COLUMN symulowane przez pełną definicję w zadaniu
`,
    seed_sql: `INSERT INTO t (id) VALUES (1);`,
    expected_result: [{ id: 1 }],
    solution_sql: "SELECT * FROM t",
    version: 1,
  },
  {
    id: "create-temp",
    theme: "polonia",
    title: "Tabela tymczasowa",
    goal: "CREATE TEMP TABLE.",
    concept: "TEMP table",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [{ ok: 1 }],
    solution_sql: "SELECT 1 AS ok",
    version: 1,
  },
  {
    id: "create-if-not-exists",
    theme: "polonia",
    title: "IF NOT EXISTS",
    goal: "CREATE TABLE IF NOT EXISTS.",
    concept: "IF NOT EXISTS",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY);`,
    seed_sql: ``,
    expected_result: [{ name: "t", type: "table" }],
    solution_sql: "SELECT name, type FROM sqlite_master WHERE type='table' AND name='t'",
    version: 1,
  },
  {
    id: "identifiers",
    theme: "polonia",
    title: "Identyfikatory",
    goal: "Cudzysłowy; unikanie słów zastrzeżonych.",
    concept: "Identifiers",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_keywords.html",
    schema_ddl: `CREATE TABLE "select" (id INTEGER PRIMARY KEY, "order" INTEGER);`,
    seed_sql: `INSERT INTO "select" (id, "order") VALUES (1, 1);`,
    expected_result: [{ id: 1, order: 1 }],
    solution_sql: 'SELECT * FROM "select"',
    version: 1,
  },
  {
    id: "create-without-rowid",
    theme: "polonia",
    title: "WITHOUT ROWID",
    goal: "Tabela bez wewnętrznego rowid.",
    concept: "WITHOUT ROWID",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtable.html",
    schema_ddl: `CREATE TABLE t (a INTEGER, b INTEGER, PRIMARY KEY (a, b)) WITHOUT ROWID;`,
    seed_sql: `INSERT INTO t (a, b) VALUES (1, 1), (1, 2);`,
    expected_result: [
      { a: 1, b: 1 },
      { a: 1, b: 2 },
    ],
    solution_sql: "SELECT * FROM t ORDER BY a, b",
    version: 1,
  },
  {
    id: "create-index-where",
    theme: "polonia",
    title: "Indeks częściowy",
    goal: "CREATE INDEX ... WHERE.",
    concept: "Partial index",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createindex.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, aktywny INTEGER, nazwa TEXT);
CREATE INDEX idx_aktywne ON t(nazwa) WHERE aktywny = 1;`,
    seed_sql: `INSERT INTO t (id, aktywny, nazwa) VALUES (1, 1, 'A'), (2, 0, 'B');`,
    expected_result: [{ name: "idx_aktywne" }],
    solution_sql: "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_aktywne'",
    version: 1,
  },
  {
    id: "create-unique-index",
    theme: "polonia",
    title: "UNIQUE INDEX",
    goal: "Indeks unikalny.",
    concept: "UNIQUE INDEX",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createindex.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, kod TEXT);
CREATE UNIQUE INDEX idx_kod ON t(kod);`,
    seed_sql: `INSERT INTO t (id, kod) VALUES (1, 'X'), (2, 'Y');`,
    expected_result: [
      { id: 1, kod: "X" },
      { id: 2, kod: "Y" },
    ],
    solution_sql: "SELECT * FROM t ORDER BY id",
    version: 1,
  },
  {
    id: "schema-name",
    theme: "polonia",
    title: "Nazwa schemy",
    goal: "main, temp, attached DB.",
    concept: "Schema name",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_attach.html",
    schema_ddl: `CREATE TABLE main.t (id INTEGER PRIMARY KEY);`,
    seed_sql: `INSERT INTO main.t (id) VALUES (1);`,
    expected_result: [{ id: 1 }],
    solution_sql: "SELECT * FROM main.t",
    version: 1,
  },
  {
    id: "create-trigger",
    theme: "polonia",
    title: "CREATE TRIGGER",
    goal: "Trigger BEFORE/AFTER INSERT/UPDATE/DELETE.",
    concept: "CREATE TRIGGER",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_createtrigger.html",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY, val INTEGER);
CREATE TABLE log (id INTEGER PRIMARY KEY, msg TEXT);
CREATE TRIGGER tr AFTER INSERT ON t BEGIN INSERT INTO log (msg) VALUES ('insert'); END;`,
    seed_sql: `INSERT INTO t (id, val) VALUES (1, 10);`,
    expected_result: [{ id: 1, msg: "insert" }],
    solution_sql: "SELECT * FROM log",
    version: 1,
  },
];
