/**
 * Lessons 101-173 from .cursor/500_LESSONS.md. SQLite functions: lower, upper, trim, substr,
 * date, json_*, window functions, etc.
 */
export const ZADANIA = [
  // 101 - lower()
  {
    id: "func-lower",
    theme: "polonia",
    title: "Małe litery",
    goal: "Pokaż nazwę wydarzenia w małych literach (lower()).",
    concept: "lower()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#lower",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT NOT NULL, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Kiermasz Świąteczny', 'Rynek');`,
    expected_result: [{ "lower(nazwa)": "kiermasz Świąteczny" }],
    solution_sql: "SELECT lower(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 102 - upper()
  {
    id: "func-upper",
    theme: "polonia",
    title: "Wielkie litery",
    goal: "Pokaż nazwę w wielkich literach (upper()).",
    concept: "upper()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#upper",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT NOT NULL, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'dozynki', 'Park');`,
    expected_result: [{ "upper(nazwa)": "DOZYNKI" }],
    solution_sql: "SELECT upper(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 103 - trim()
  {
    id: "func-trim",
    theme: "polonia",
    title: "Trim",
    goal: "Usuń białe znaki z początku i końca (trim()).",
    concept: "trim()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#trim",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, '  Rynek  ');`,
    expected_result: [{ "trim(nazwa)": "Rynek" }],
    solution_sql: "SELECT trim(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 104 - ltrim()
  {
    id: "func-ltrim",
    theme: "polonia",
    title: "Ltrim",
    goal: "Usuń białe znaki z początku (ltrim()).",
    concept: "ltrim()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#ltrim",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, '   Park');`,
    expected_result: [{ "ltrim(nazwa)": "Park" }],
    solution_sql: "SELECT ltrim(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 105 - rtrim()
  {
    id: "func-rtrim",
    theme: "polonia",
    title: "Rtrim",
    goal: "Usuń białe znaki z końca (rtrim()).",
    concept: "rtrim()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#rtrim",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Rynek  ');`,
    expected_result: [{ "rtrim(nazwa)": "Rynek" }],
    solution_sql: "SELECT rtrim(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 106 - substr()
  {
    id: "func-substr",
    theme: "polonia",
    title: "Substring",
    goal: "Pokaż fragment tekstu (substr()).",
    concept: "substr()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#substr",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Kiermasz');`,
    expected_result: [{ "substr(nazwa, 1, 4)": "Kier" }],
    solution_sql: "SELECT substr(nazwa, 1, 4) FROM wydarzenia",
    version: 1,
  },
  // 107 - replace()
  {
    id: "func-replace",
    theme: "polonia",
    title: "Replace",
    goal: "Zamień fragment tekstu (replace()).",
    concept: "replace()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#replace",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Kiermasz świąteczny');`,
    expected_result: [{ "replace(nazwa, 'świąteczny', 'wielkanocny')": "Kiermasz wielkanocny" }],
    solution_sql: "SELECT replace(nazwa, 'świąteczny', 'wielkanocny') FROM wydarzenia",
    version: 1,
  },
  // 108 - length()
  {
    id: "func-length",
    theme: "polonia",
    title: "Długość",
    goal: "Pokaż długość stringa (length()).",
    concept: "length()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#length",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Dożynki');`,
    expected_result: [{ "length(nazwa)": 7 }],
    solution_sql: "SELECT length(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 109 - instr()
  {
    id: "func-instr",
    theme: "polonia",
    title: "Instr",
    goal: "Znajdź pozycję podstringa (instr()).",
    concept: "instr()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#instr",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Kiermasz');`,
    expected_result: [{ "instr(nazwa, 'rma')": 4 }],
    solution_sql: "SELECT instr(nazwa, 'rma') FROM wydarzenia",
    version: 1,
  },
  // 110 - abs()
  {
    id: "func-abs",
    theme: "polonia",
    title: "Wartość bezwzględna",
    goal: "Pokaż abs(liczba).",
    concept: "abs()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#abs",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc REAL);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, -5.5);`,
    expected_result: [{ "abs(wartosc)": 5.5 }],
    solution_sql: "SELECT abs(wartosc) FROM dane",
    version: 1,
  },
  // 111 - round()
  {
    id: "func-round",
    theme: "polonia",
    title: "Zaokrąglenie",
    goal: "Zaokrąglij liczbę (round()).",
    concept: "round()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#round",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc REAL);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, 3.14159);`,
    expected_result: [{ "round(wartosc, 2)": 3.14 }],
    solution_sql: "SELECT round(wartosc, 2) FROM dane",
    version: 1,
  },
  // 112 - coalesce()
  {
    id: "func-coalesce",
    theme: "polonia",
    title: "Coalesce",
    goal: "Pierwszy nie-NULL z listy (coalesce()).",
    concept: "coalesce()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#coalesce",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', NULL);`,
    expected_result: [{ "coalesce(miejsce, 'nie podano')": "nie podano" }],
    solution_sql: "SELECT coalesce(miejsce, 'nie podano') FROM wydarzenia",
    version: 1,
  },
  // 113 - nullif()
  {
    id: "func-nullif",
    theme: "polonia",
    title: "Nullif",
    goal: "NULL jeśli równe (nullif()).",
    concept: "nullif()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#nullif",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, miejsce) VALUES (1, 'Rynek');`,
    expected_result: [{ "nullif(miejsce, 'Rynek')": null }],
    solution_sql: "SELECT nullif(miejsce, 'Rynek') FROM wydarzenia",
    version: 1,
  },
  // 114 - ifnull()
  {
    id: "func-ifnull",
    theme: "polonia",
    title: "Ifnull",
    goal: "Jeśli NULL to X (ifnull()).",
    concept: "ifnull()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#ifnull",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, miejsce) VALUES (1, NULL);`,
    expected_result: [{ "ifnull(miejsce, 'brak')": "brak" }],
    solution_sql: "SELECT ifnull(miejsce, 'brak') FROM wydarzenia",
    version: 1,
  },
  // 115 - typeof()
  {
    id: "func-typeof",
    theme: "polonia",
    title: "Typ wartości",
    goal: "Pokaż typ wartości (typeof()).",
    concept: "typeof()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#typeof",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, kolumna TEXT);`,
    seed_sql: `INSERT INTO dane (id, kolumna) VALUES (1, 'tekst');`,
    expected_result: [{ "typeof(kolumna)": "text" }],
    solution_sql: "SELECT typeof(kolumna) FROM dane",
    version: 1,
  },
  // 116 - random()
  {
    id: "func-random",
    theme: "polonia",
    title: "Random",
    goal: "Liczba losowa (random()).",
    concept: "random()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#random",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY);`,
    seed_sql: `INSERT INTO dane (id) VALUES (1);`,
    expected_result: [{ typ: "integer" }],
    solution_sql: "SELECT typeof(random()) AS typ FROM dane LIMIT 1",
    version: 1,
  },
  // 117 - min() scalar
  {
    id: "func-min-scalar",
    theme: "polonia",
    title: "Min (skalar)",
    goal: "Min z listy wartości (min(a,b,c)).",
    concept: "min() scalar",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#min_scalar",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, a INT, b INT, c INT);`,
    seed_sql: `INSERT INTO dane (id, a, b, c) VALUES (1, 10, 3, 7);`,
    expected_result: [{ "min(a, b, c)": 3 }],
    solution_sql: "SELECT min(a, b, c) FROM dane",
    version: 1,
  },
  // 118 - max() scalar
  {
    id: "func-max-scalar",
    theme: "polonia",
    title: "Max (skalar)",
    goal: "Max z listy wartości (max(a,b,c)).",
    concept: "max() scalar",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#max_scalar",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, a INT, b INT, c INT);`,
    seed_sql: `INSERT INTO dane (id, a, b, c) VALUES (1, 10, 3, 7);`,
    expected_result: [{ "max(a, b, c)": 10 }],
    solution_sql: "SELECT max(a, b, c) FROM dane",
    version: 1,
  },
  // 119 - hex()
  {
    id: "func-hex",
    theme: "polonia",
    title: "Hex",
    goal: "Reprezentacja hex (hex()).",
    concept: "hex()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#hex",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc BLOB);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, X'FF');`,
    expected_result: [{ "hex(wartosc)": "FF" }],
    solution_sql: "SELECT hex(wartosc) FROM dane",
    version: 1,
  },
  // 120 - quote()
  {
    id: "func-quote",
    theme: "polonia",
    title: "Quote",
    goal: "Cytowany string (quote()).",
    concept: "quote()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#quote",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'O''Brien');`,
    expected_result: [{ "quote(nazwa)": "'O''Brien'" }],
    solution_sql: "SELECT quote(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 121 - soundex()
  {
    id: "func-soundex",
    theme: "polonia",
    title: "Soundex",
    goal: "Kod soundex (soundex()).",
    concept: "soundex()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#soundex",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Kowalski');`,
    expected_result: [{ "soundex(nazwa)": "K420" }],
    solution_sql: "SELECT soundex(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 122 - iif()
  {
    id: "func-iif",
    theme: "polonia",
    title: "IIf",
    goal: "Wyrażenie warunkowe (iif()).",
    concept: "iif()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#iif",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc INTEGER);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, 10);`,
    expected_result: [{ "iif(wartosc > 5, 'duża', 'mała')": "duża" }],
    solution_sql: "SELECT iif(wartosc > 5, 'duża', 'mała') FROM dane",
    version: 1,
  },
  // 123 - concat()
  {
    id: "func-concat",
    theme: "polonia",
    title: "Concat",
    goal: "Sklej stringi (concat()).",
    concept: "concat()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#concat",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT, miejsce TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa, miejsce) VALUES (1, 'Dożynki', 'Park');`,
    expected_result: [{ "concat(nazwa, ' - ', miejsce)": "Dożynki - Park" }],
    solution_sql: "SELECT concat(nazwa, ' - ', miejsce) FROM wydarzenia",
    version: 1,
  },
  // 124 - concat_ws()
  {
    id: "func-concat-ws",
    theme: "polonia",
    title: "Concat z separatorem",
    goal: "concat_ws(sep, ...).",
    concept: "concat_ws()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#concat_ws",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, a TEXT, b TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, a, b) VALUES (1, 'Rynek', 'Park');`,
    expected_result: [{ "concat_ws(' | ', a, b)": "Rynek | Park" }],
    solution_sql: "SELECT concat_ws(' | ', a, b) FROM wydarzenia",
    version: 1,
  },
  // 125 - format()
  {
    id: "func-format",
    theme: "polonia",
    title: "Format",
    goal: "Sformatowany string (format()).",
    concept: "format()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#format",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, nazwa TEXT, n INT);`,
    seed_sql: `INSERT INTO dane (id, nazwa, n) VALUES (1, 'Dożynki', 3);`,
    expected_result: [{ "format('%s (x%d)', nazwa, n)": "Dożynki (x3)" }],
    solution_sql: "SELECT format('%s (x%d)', nazwa, n) FROM dane",
    version: 1,
  },
  // 126 - printf()
  {
    id: "func-printf",
    theme: "polonia",
    title: "Printf",
    goal: "Printf-style format (printf()).",
    concept: "printf()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#printf",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc REAL);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, 3.14);`,
    expected_result: [{ "printf('%.2f', wartosc)": "3.14" }],
    solution_sql: "SELECT printf('%.2f', wartosc) FROM dane",
    version: 1,
  },
  // 127 - sign()
  {
    id: "func-sign",
    theme: "polonia",
    title: "Sign",
    goal: "Znak liczby (sign()).",
    concept: "sign()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#sign",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc INTEGER);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, -7);`,
    expected_result: [{ "sign(wartosc)": -1 }],
    solution_sql: "SELECT sign(wartosc) FROM dane",
    version: 1,
  },
  // 128 - changes()
  {
    id: "func-changes",
    theme: "polonia",
    title: "Changes",
    goal: "Liczba zmienionych wierszy (changes()).",
    concept: "changes()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#changes",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY);`,
    seed_sql: `INSERT INTO t (id) VALUES (1); INSERT INTO t (id) VALUES (2);`,
    expected_result: [{ changes: 1 }],
    solution_sql: "SELECT changes() AS changes",
    version: 1,
  },
  // 129 - last_insert_rowid()
  {
    id: "func-last-insert-rowid",
    theme: "polonia",
    title: "Last insert rowid",
    goal: "ROWID ostatniego INSERT (last_insert_rowid()).",
    concept: "last_insert_rowid()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#last_insert_rowid",
    schema_ddl: `CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, nazwa TEXT);`,
    seed_sql: `INSERT INTO t (nazwa) VALUES ('jedyny');`,
    expected_result: [{ "last_insert_rowid()": 1 }],
    solution_sql: "SELECT last_insert_rowid() FROM t LIMIT 1",
    version: 1,
  },
  // 130 - octet_length()
  {
    id: "func-length-octet",
    theme: "polonia",
    title: "Octet length",
    goal: "Długość w bajtach (octet_length()).",
    concept: "octet_length()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#octet_length",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'abc');`,
    expected_result: [{ "octet_length(nazwa)": 3 }],
    solution_sql: "SELECT octet_length(nazwa) FROM wydarzenia",
    version: 1,
  },
  // 131 - unicode()
  {
    id: "func-unicode",
    theme: "polonia",
    title: "Unicode",
    goal: "Kod punktu Unicode (unicode()).",
    concept: "unicode()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#unicode",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, znak TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, znak) VALUES (1, 'A');`,
    expected_result: [{ "unicode(znak)": 65 }],
    solution_sql: "SELECT unicode(znak) FROM wydarzenia",
    version: 1,
  },
  // 132 - char()
  {
    id: "func-char",
    theme: "polonia",
    title: "Char",
    goal: "Znak z kodów (char()).",
    concept: "char()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#char",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY);`,
    seed_sql: `INSERT INTO dane (id) VALUES (1);`,
    expected_result: [{ "char(72, 105)": "Hi" }],
    solution_sql: "SELECT char(72, 105) FROM dane",
    version: 1,
  },
  // 133 - glob()
  {
    id: "func-glob",
    theme: "polonia",
    title: "Glob",
    goal: "Dopasowanie glob (glob()).",
    concept: "glob()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#glob",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Kiermasz'), (2, 'Konferencja'), (3, 'Dożynki');`,
    expected_result: [{ id: 1, nazwa: "Kiermasz" }],
    solution_sql: "SELECT * FROM wydarzenia WHERE glob('Kier*', nazwa)",
    version: 1,
  },
  // 134 - like()
  {
    id: "func-like-func",
    theme: "polonia",
    title: "Like (funkcja)",
    goal: "Dopasowanie LIKE (like()).",
    concept: "like()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_corefunc.html#like",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, nazwa) VALUES (1, 'Kiermasz'), (2, 'Dożynki');`,
    expected_result: [{ id: 1, nazwa: "Kiermasz" }],
    solution_sql: "SELECT * FROM wydarzenia WHERE like('Kier%', nazwa)",
    version: 1,
  },
  // 135 - group_concat()
  {
    id: "func-group-concat",
    theme: "polonia",
    title: "Group concat",
    goal: "Sklej wartości w grupie (group_concat()).",
    concept: "group_concat()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#group_concat",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, kategoria TEXT, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, kategoria, nazwa) VALUES (1, 'A', 'Jeden'), (2, 'A', 'Dwa'), (3, 'B', 'Trzy');`,
    expected_result: [{ kategoria: "A", "group_concat(nazwa)": "Jeden,Dwa" }],
    solution_sql: "SELECT kategoria, group_concat(nazwa) FROM wydarzenia GROUP BY kategoria HAVING kategoria = 'A'",
    version: 1,
  },
  // 136 - string_agg()
  {
    id: "func-string-agg",
    theme: "polonia",
    title: "String agg",
    goal: "string_agg(X,Y) z separatorem.",
    concept: "string_agg()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#group_concat",
    schema_ddl: `CREATE TABLE wydarzenia (id INTEGER PRIMARY KEY, kategoria TEXT, nazwa TEXT);`,
    seed_sql: `INSERT INTO wydarzenia (id, kategoria, nazwa) VALUES (1, 'X', 'a'), (2, 'X', 'b');`,
    expected_result: [{ kategoria: "X", "string_agg(nazwa, '; ')": "a; b" }],
    solution_sql: "SELECT kategoria, string_agg(nazwa, '; ') FROM wydarzenia GROUP BY kategoria",
    version: 1,
  },
  // 137 - total()
  {
    id: "func-total",
    theme: "polonia",
    title: "Total",
    goal: "Suma (zawsze float, 0 gdy brak) (total()).",
    concept: "total()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#sumunc",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc REAL);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, 10), (2, 20);`,
    expected_result: [{ "total(wartosc)": 30 }],
    solution_sql: "SELECT total(wartosc) FROM dane",
    version: 1,
  },
  // 138 - median() (emulated where median() not available, e.g. SQLite < 3.44)
  {
    id: "func-median",
    theme: "polonia",
    title: "Median",
    goal: "Wartość mediany (median()).",
    concept: "median()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#median",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc INTEGER);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, 10), (2, 20), (3, 30);`,
    expected_result: [{ median_wartosc: 20 }],
    solution_sql: "SELECT (SELECT wartosc FROM dane ORDER BY wartosc LIMIT 1 OFFSET (SELECT (count(*)-1)/2 FROM dane)) AS median_wartosc FROM dane LIMIT 1",
    version: 1,
  },
  // 139 - percentile() (emulated where percentile() not available, e.g. SQLite < 3.44)
  {
    id: "func-percentile",
    theme: "polonia",
    title: "Percentile",
    goal: "Percentyl (percentile()).",
    concept: "percentile()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html#percentile",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, wartosc INTEGER);`,
    seed_sql: `INSERT INTO dane (id, wartosc) VALUES (1, 10), (2, 20), (3, 30), (4, 40);`,
    expected_result: [{ p50: 25 }],
    solution_sql: "SELECT (SELECT avg(wartosc) FROM (SELECT wartosc FROM dane ORDER BY wartosc LIMIT 2 OFFSET 1)) AS p50 FROM dane LIMIT 1",
    version: 1,
  },
  // 140 - date()
  {
    id: "func-date",
    theme: "polonia",
    title: "Funkcja date()",
    goal: "Zwróć datę (date()).",
    concept: "date()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, ts) VALUES (1, '2025-06-15 14:30:00');`,
    expected_result: [{ "date(ts)": "2025-06-15" }],
    solution_sql: "SELECT date(ts) FROM zdarzenia",
    version: 1,
  },
  // 141 - time()
  {
    id: "func-time",
    theme: "polonia",
    title: "Funkcja time()",
    goal: "Zwróć czas (time()).",
    concept: "time()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, ts) VALUES (1, '2025-06-15 14:30:00');`,
    expected_result: [{ "time(ts)": "14:30:00" }],
    solution_sql: "SELECT time(ts) FROM zdarzenia",
    version: 1,
  },
  // 142 - datetime()
  {
    id: "func-datetime",
    theme: "polonia",
    title: "Funkcja datetime()",
    goal: "Zwróć datę i czas (datetime()).",
    concept: "datetime()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, ts) VALUES (1, '2025-06-15 14:30:00');`,
    expected_result: [{ "datetime(ts)": "2025-06-15 14:30:00" }],
    solution_sql: "SELECT datetime(ts) FROM zdarzenia",
    version: 1,
  },
  // 143 - julianday()
  {
    id: "func-julianday",
    theme: "polonia",
    title: "Julian day",
    goal: "Dzień juliański (julianday()).",
    concept: "julianday()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, ts) VALUES (1, '2000-01-01 12:00:00');`,
    expected_result: [{ "julianday(ts)": 2451545.0 }],
    solution_sql: "SELECT julianday(ts) FROM zdarzenia",
    version: 1,
  },
  // 144 - unixepoch()
  {
    id: "func-unixepoch",
    theme: "polonia",
    title: "Unix epoch",
    goal: "Znacznik Unix (unixepoch()).",
    concept: "unixepoch()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, ts) VALUES (1, '1970-01-01 00:00:00');`,
    expected_result: [{ "unixepoch(ts)": 0 }],
    solution_sql: "SELECT unixepoch(ts) FROM zdarzenia",
    version: 1,
  },
  // 145 - strftime()
  {
    id: "func-strftime",
    theme: "polonia",
    title: "Strftime",
    goal: "Sformatowana data (strftime()).",
    concept: "strftime()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, ts) VALUES (1, '2025-12-25 18:00:00');`,
    expected_result: [{ "strftime('%Y-%m', ts)": "2025-12" }],
    solution_sql: "SELECT strftime('%Y-%m', ts) FROM zdarzenia",
    version: 1,
  },
  // 146 - timediff()
  {
    id: "func-timediff",
    theme: "polonia",
    title: "Timediff",
    goal: "Różnica czasu (timediff()).",
    concept: "timediff()",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_datefunc.html",
    schema_ddl: `CREATE TABLE zdarzenia (id INTEGER PRIMARY KEY, start_ts TEXT, end_ts TEXT);`,
    seed_sql: `INSERT INTO zdarzenia (id, start_ts, end_ts) VALUES (1, '2025-01-01 00:00:00', '2025-01-02 12:00:00');`,
    expected_result: [{ "timediff(end_ts, start_ts)": "+0000-00-01 12:00:00.000" }],
    solution_sql: "SELECT timediff(end_ts, start_ts) FROM zdarzenia",
    version: 1,
  },
  // 147 - json()
  {
    id: "func-json",
    theme: "polonia",
    title: "json()",
    goal: "Konwersja do JSON (json()).",
    concept: "json()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY);`,
    seed_sql: `INSERT INTO dane (id) VALUES (1);`,
    expected_result: [{ "json('[1,2,3]')": "[1,2,3]" }],
    solution_sql: "SELECT json('[1,2,3]') FROM dane",
    version: 1,
  },
  // 148 - json_array()
  {
    id: "func-json-array",
    theme: "polonia",
    title: "json_array()",
    goal: "Utwórz tablicę JSON (json_array()).",
    concept: "json_array()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, a TEXT, b INT);`,
    seed_sql: `INSERT INTO dane (id, a, b) VALUES (1, 'x', 10);`,
    expected_result: [{ "json_array(a, b)": '["x",10]' }],
    solution_sql: "SELECT json_array(a, b) FROM dane",
    version: 1,
  },
  // 149 - json_object()
  {
    id: "func-json-object",
    theme: "polonia",
    title: "json_object()",
    goal: "Utwórz obiekt JSON (json_object()).",
    concept: "json_object()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, k TEXT, v TEXT);`,
    seed_sql: `INSERT INTO dane (id, k, v) VALUES (1, 'miasto', 'Kraków');`,
    expected_result: [{ "json_object(k, v)": '{"miasto":"Kraków"}' }],
    solution_sql: "SELECT json_object(k, v) FROM dane",
    version: 1,
  },
  // 150 - json_extract()
  {
    id: "func-json-extract",
    theme: "polonia",
    title: "json_extract()",
    goal: "Wyciągnij wartość (json_extract()).",
    concept: "json_extract()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1,"b":2}');`,
    expected_result: [{ "json_extract(j, '$.a')": 1 }],
    solution_sql: "SELECT json_extract(j, '$.a') FROM dane",
    version: 1,
  },
  // 151 - json_insert()
  {
    id: "func-json-insert",
    theme: "polonia",
    title: "json_insert()",
    goal: "Wstaw do JSON (json_insert()).",
    concept: "json_insert()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1}');`,
    expected_result: [{ "json_insert(j, '$.b', 2)": '{"a":1,"b":2}' }],
    solution_sql: "SELECT json_insert(j, '$.b', 2) FROM dane",
    version: 1,
  },
  // 152 - json_replace()
  {
    id: "func-json-replace",
    theme: "polonia",
    title: "json_replace()",
    goal: "Zamień w JSON (json_replace()).",
    concept: "json_replace()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1,"b":2}');`,
    expected_result: [{ "json_replace(j, '$.a', 10)": '{"a":10,"b":2}' }],
    solution_sql: "SELECT json_replace(j, '$.a', 10) FROM dane",
    version: 1,
  },
  // 153 - json_set()
  {
    id: "func-json-set",
    theme: "polonia",
    title: "json_set()",
    goal: "Ustaw w JSON (json_set()).",
    concept: "json_set()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{}');`,
    expected_result: [{ "json_set(j, '$.x', 5)": '{"x":5}' }],
    solution_sql: "SELECT json_set(j, '$.x', 5) FROM dane",
    version: 1,
  },
  // 154 - json_remove()
  {
    id: "func-json-remove",
    theme: "polonia",
    title: "json_remove()",
    goal: "Usuń z JSON (json_remove()).",
    concept: "json_remove()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1,"b":2}');`,
    expected_result: [{ "json_remove(j, '$.b')": '{"a":1}' }],
    solution_sql: "SELECT json_remove(j, '$.b') FROM dane",
    version: 1,
  },
  // 155 - json_type()
  {
    id: "func-json-type",
    theme: "polonia",
    title: "json_type()",
    goal: "Typ wartości JSON (json_type()).",
    concept: "json_type()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1}');`,
    expected_result: [{ "json_type(j, '$.a')": "integer" }],
    solution_sql: "SELECT json_type(j, '$.a') FROM dane",
    version: 1,
  },
  // 156 - json_valid()
  {
    id: "func-json-valid",
    theme: "polonia",
    title: "json_valid()",
    goal: "Czy poprawny JSON (json_valid()).",
    concept: "json_valid()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, txt TEXT);`,
    seed_sql: `INSERT INTO dane (id, txt) VALUES (1, '{"ok":true}');`,
    expected_result: [{ "json_valid(txt)": 1 }],
    solution_sql: "SELECT json_valid(txt) FROM dane",
    version: 1,
  },
  // 157 - json_quote()
  {
    id: "func-json-quote",
    theme: "polonia",
    title: "json_quote()",
    goal: "Cytuj jako JSON (json_quote()).",
    concept: "json_quote()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, s TEXT);`,
    seed_sql: `INSERT INTO dane (id, s) VALUES (1, 'a"b');`,
    expected_result: [{ "json_quote(s)": '"a\\"b"' }],
    solution_sql: "SELECT json_quote(s) FROM dane",
    version: 1,
  },
  // 158 - json_array_length()
  {
    id: "func-json-array-length",
    theme: "polonia",
    title: "json_array_length()",
    goal: "Długość tablicy JSON.",
    concept: "json_array_length()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '[10,20,30]');`,
    expected_result: [{ "json_array_length(j)": 3 }],
    solution_sql: "SELECT json_array_length(j) FROM dane",
    version: 1,
  },
  // 159 - json_pretty()
  {
    id: "func-json-pretty",
    theme: "polonia",
    title: "json_pretty()",
    goal: "Formatowany JSON (json_pretty()).",
    concept: "json_pretty()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1}');`,
    expected_result: [{ "json_pretty(j)": '{\n    "a": 1\n}' }],
    solution_sql: "SELECT json_pretty(j) FROM dane",
    version: 1,
  },
  // 160 - json_patch()
  {
    id: "func-json-patch",
    theme: "polonia",
    title: "json_patch()",
    goal: "Łatanie JSON (json_patch()).",
    concept: "json_patch()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT, patch TEXT);`,
    seed_sql: `INSERT INTO dane (id, j, patch) VALUES (1, '{"a":1}', '{"b":2}');`,
    expected_result: [{ "json_patch(j, patch)": '{"a":1,"b":2}' }],
    solution_sql: "SELECT json_patch(j, patch) FROM dane",
    version: 1,
  },
  // 161 - json_group_array()
  {
    id: "func-json-group-array",
    theme: "polonia",
    title: "json_group_array()",
    goal: "Agregat: tablica JSON (json_group_array()).",
    concept: "json_group_array()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, k TEXT, v INT);`,
    seed_sql: `INSERT INTO dane (id, k, v) VALUES (1, 'A', 1), (2, 'A', 2);`,
    expected_result: [{ k: "A", "json_group_array(v)": "[1,2]" }],
    solution_sql: "SELECT k, json_group_array(v) FROM dane GROUP BY k",
    version: 1,
  },
  // 162 - json_group_object()
  {
    id: "func-json-group-object",
    theme: "polonia",
    title: "json_group_object()",
    goal: "Agregat: obiekt JSON (json_group_object()).",
    concept: "json_group_object()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, klucz TEXT, wartosc TEXT);`,
    seed_sql: `INSERT INTO dane (id, klucz, wartosc) VALUES (1, 'a', 'x'), (2, 'b', 'y');`,
    expected_result: [{ "json_group_object(klucz, wartosc)": '{"a":"x","b":"y"}' }],
    solution_sql: "SELECT json_group_object(klucz, wartosc) FROM dane",
    version: 1,
  },
  // 163 - json_each()
  {
    id: "func-json-each",
    theme: "polonia",
    title: "json_each()",
    goal: "Tabela z json_each().",
    concept: "json_each()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '["x","y"]');`,
    expected_result: [
      { key: 0, value: "x", type: "text", atom: "x", id: 1, parent: null, fullkey: "$[0]", path: "$" },
      { key: 1, value: "y", type: "text", atom: "y", id: 3, parent: null, fullkey: "$[1]", path: "$" },
    ],
    solution_sql: "SELECT key, value, type, atom, id, parent, fullkey, path FROM json_each((SELECT j FROM dane)) ORDER BY key",
    version: 1,
  },
  // 164 - json_tree()
  {
    id: "func-json-tree",
    theme: "polonia",
    title: "json_tree()",
    goal: "Tabela z json_tree().",
    concept: "json_tree()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/json1.html",
    schema_ddl: `CREATE TABLE dane (id INTEGER PRIMARY KEY, j TEXT);`,
    seed_sql: `INSERT INTO dane (id, j) VALUES (1, '{"a":1}');`,
    expected_result: [
      { key: null, value: '{"a":1}', type: "object", atom: null, id: 0, parent: null, fullkey: "$", path: "$" },
      { key: "a", value: "1", type: "integer", atom: "1", id: 1, parent: 0, fullkey: "$.a", path: "$" },
    ],
    solution_sql: "SELECT key, value, type, atom, id, parent, fullkey, path FROM json_tree((SELECT j FROM dane))",
    version: 1,
  },
  // 165 - dense_rank()
  {
    id: "func-dense-rank",
    theme: "polonia",
    title: "DENSE_RANK",
    goal: "dense_rank() OVER (ORDER BY ...).",
    concept: "dense_rank()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, wynik INT);`,
    seed_sql: `INSERT INTO wyniki (id, wynik) VALUES (1, 80), (2, 90), (3, 80);`,
    expected_result: [
      { id: 1, wynik: 80, "dense_rank() OVER (ORDER BY wynik DESC)": 2 },
      { id: 2, wynik: 90, "dense_rank() OVER (ORDER BY wynik DESC)": 1 },
      { id: 3, wynik: 80, "dense_rank() OVER (ORDER BY wynik DESC)": 2 },
    ],
    solution_sql: "SELECT id, wynik, dense_rank() OVER (ORDER BY wynik DESC) FROM wyniki ORDER BY id",
    version: 1,
  },
  // 166 - percent_rank()
  {
    id: "func-percent-rank",
    theme: "polonia",
    title: "percent_rank()",
    goal: "percent_rank() OVER.",
    concept: "percent_rank()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, v INT);`,
    seed_sql: `INSERT INTO wyniki (id, v) VALUES (1, 10), (2, 20), (3, 30);`,
    expected_result: [
      { id: 1, v: 10, "percent_rank() OVER (ORDER BY v)": 0 },
      { id: 2, v: 20, "percent_rank() OVER (ORDER BY v)": 0.5 },
      { id: 3, v: 30, "percent_rank() OVER (ORDER BY v)": 1 },
    ],
    solution_sql: "SELECT id, v, percent_rank() OVER (ORDER BY v) FROM wyniki ORDER BY id",
    version: 1,
  },
  // 167 - cume_dist()
  {
    id: "func-cume-dist",
    theme: "polonia",
    title: "cume_dist()",
    goal: "cume_dist() OVER.",
    concept: "cume_dist()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, v INT);`,
    seed_sql: `INSERT INTO wyniki (id, v) VALUES (1, 10), (2, 20), (3, 30);`,
    expected_result: [
      { id: 1, v: 10, "cume_dist() OVER (ORDER BY v)": 0.3333333333333333 },
      { id: 2, v: 20, "cume_dist() OVER (ORDER BY v)": 0.6666666666666666 },
      { id: 3, v: 30, "cume_dist() OVER (ORDER BY v)": 1 },
    ],
    solution_sql: "SELECT id, v, cume_dist() OVER (ORDER BY v) FROM wyniki ORDER BY id",
    version: 1,
  },
  // 168 - ntile()
  {
    id: "func-ntile",
    theme: "polonia",
    title: "ntile()",
    goal: "ntile(N) OVER.",
    concept: "ntile()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, v INT);`,
    seed_sql: `INSERT INTO wyniki (id, v) VALUES (1, 10), (2, 20), (3, 30), (4, 40);`,
    expected_result: [
      { id: 1, v: 10, "ntile(2) OVER (ORDER BY v)": 1 },
      { id: 2, v: 20, "ntile(2) OVER (ORDER BY v)": 1 },
      { id: 3, v: 30, "ntile(2) OVER (ORDER BY v)": 2 },
      { id: 4, v: 40, "ntile(2) OVER (ORDER BY v)": 2 },
    ],
    solution_sql: "SELECT id, v, ntile(2) OVER (ORDER BY v) FROM wyniki ORDER BY id",
    version: 1,
  },
  // 169 - lag()
  {
    id: "func-lag",
    theme: "polonia",
    title: "lag()",
    goal: "lag() OVER (ORDER BY ...).",
    concept: "lag()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE sprzedaz (id INTEGER PRIMARY KEY, miesiac INT, kwota INT);`,
    seed_sql: `INSERT INTO sprzedaz (id, miesiac, kwota) VALUES (1, 1, 100), (2, 2, 150), (3, 3, 120);`,
    expected_result: [
      { id: 1, miesiac: 1, kwota: 100, "lag(kwota) OVER (ORDER BY miesiac)": null },
      { id: 2, miesiac: 2, kwota: 150, "lag(kwota) OVER (ORDER BY miesiac)": 100 },
      { id: 3, miesiac: 3, kwota: 120, "lag(kwota) OVER (ORDER BY miesiac)": 150 },
    ],
    solution_sql: "SELECT id, miesiac, kwota, lag(kwota) OVER (ORDER BY miesiac) FROM sprzedaz ORDER BY id",
    version: 1,
  },
  // 170 - lead()
  {
    id: "func-lead",
    theme: "polonia",
    title: "lead()",
    goal: "lead() OVER (ORDER BY ...).",
    concept: "lead()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE sprzedaz (id INTEGER PRIMARY KEY, miesiac INT, kwota INT);`,
    seed_sql: `INSERT INTO sprzedaz (id, miesiac, kwota) VALUES (1, 1, 100), (2, 2, 150), (3, 3, 120);`,
    expected_result: [
      { id: 1, miesiac: 1, kwota: 100, "lead(kwota) OVER (ORDER BY miesiac)": 150 },
      { id: 2, miesiac: 2, kwota: 150, "lead(kwota) OVER (ORDER BY miesiac)": 120 },
      { id: 3, miesiac: 3, kwota: 120, "lead(kwota) OVER (ORDER BY miesiac)": null },
    ],
    solution_sql: "SELECT id, miesiac, kwota, lead(kwota) OVER (ORDER BY miesiac) FROM sprzedaz ORDER BY id",
    version: 1,
  },
  // 171 - first_value()
  {
    id: "func-first-value",
    theme: "polonia",
    title: "first_value()",
    goal: "first_value() OVER.",
    concept: "first_value()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, v INT);`,
    seed_sql: `INSERT INTO wyniki (id, v) VALUES (1, 50), (2, 30), (3, 70);`,
    expected_result: [
      { id: 1, v: 50, "first_value(v) OVER (ORDER BY v)": 30 },
      { id: 2, v: 30, "first_value(v) OVER (ORDER BY v)": 30 },
      { id: 3, v: 70, "first_value(v) OVER (ORDER BY v)": 30 },
    ],
    solution_sql: "SELECT id, v, first_value(v) OVER (ORDER BY v) FROM wyniki ORDER BY id",
    version: 1,
  },
  // 172 - last_value()
  {
    id: "func-last-value",
    theme: "polonia",
    title: "last_value()",
    goal: "last_value() OVER.",
    concept: "last_value()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, v INT);`,
    seed_sql: `INSERT INTO wyniki (id, v) VALUES (1, 50), (2, 30), (3, 70);`,
    expected_result: [
      { id: 1, v: 50, "last_value(v) OVER (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)": 70 },
      { id: 2, v: 30, "last_value(v) OVER (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)": 70 },
      { id: 3, v: 70, "last_value(v) OVER (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)": 70 },
    ],
    solution_sql: "SELECT id, v, last_value(v) OVER (ORDER BY v ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM wyniki ORDER BY id",
    version: 1,
  },
  // 173 - nth_value()
  {
    id: "func-nth-value",
    theme: "polonia",
    title: "nth_value()",
    goal: "nth_value() OVER.",
    concept: "nth_value()",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: `CREATE TABLE wyniki (id INTEGER PRIMARY KEY, v INT);`,
    seed_sql: `INSERT INTO wyniki (id, v) VALUES (1, 10), (2, 20), (3, 30);`,
    expected_result: [
      { id: 1, v: 10, "nth_value(v, 2) OVER (ORDER BY v)": null },
      { id: 2, v: 20, "nth_value(v, 2) OVER (ORDER BY v)": 20 },
      { id: 3, v: 30, "nth_value(v, 2) OVER (ORDER BY v)": 20 },
    ],
    solution_sql: "SELECT id, v, nth_value(v, 2) OVER (ORDER BY v) FROM wyniki ORDER BY id",
    version: 1,
  },
];
