/**
 * Lessons 51-100 from .cursor/500_LESSONS.md. JOIN schema: miejsca(id, nazwa), wydarzenia(id, nazwa, data_wydarzenia, miejsce_id).
 */
const SCHEMA_DDL = `CREATE TABLE miejsca (
  id INTEGER PRIMARY KEY,
  nazwa TEXT NOT NULL
);
CREATE TABLE wydarzenia (
  id INTEGER PRIMARY KEY,
  nazwa TEXT NOT NULL,
  data_wydarzenia DATE,
  miejsce_id INTEGER REFERENCES miejsca(id)
);`;

const SEED_SQL = `INSERT INTO miejsca (id, nazwa) VALUES
(1, 'Rynek'),
(2, 'Park miejski'),
(3, 'Dom parafialny'),
(4, 'Sala');
INSERT INTO wydarzenia (id, nazwa, data_wydarzenia, miejsce_id) VALUES
(1, 'Dożynki', '2025-09-14', 2),
(2, 'Spotkanie cechu', '2025-10-01', 3),
(3, 'Kiermasz świąteczny', '2025-12-07', 1),
(4, 'Jarmark', '2025-11-15', 1),
(5, 'Bez miejsca', '2025-08-01', NULL);`;

export const ZADANIA = [
  {
    id: "agg-var-51",
    theme: "polonia",
    title: "GROUP BY wyrażenie",
    goal: "GROUP BY z wyrażeniem (np. rok).",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ rok: "2025", cnt: 5 }],
    solution_sql: "SELECT strftime('%Y', data_wydarzenia) AS rok, COUNT(*) AS cnt FROM wydarzenia GROUP BY strftime('%Y', data_wydarzenia)",
    version: 1,
  },
  {
    id: "agg-var-52",
    theme: "polonia",
    title: "Agregat w podzapytaniu",
    goal: "Użyj agregatu w podzapytaniu.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ total: 5 }],
    solution_sql: "SELECT (SELECT COUNT(*) FROM wydarzenia) AS total",
    version: 1,
  },
  {
    id: "agg-var-53",
    theme: "polonia",
    title: "Empty group",
    goal: "Zachowanie gdy GROUP BY daje 0 wierszy.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [],
    solution_sql: "SELECT miejsce_id, COUNT(*) AS cnt FROM wydarzenia WHERE 1=0 GROUP BY miejsce_id",
    version: 1,
  },
  {
    id: "agg-var-54",
    theme: "polonia",
    title: "Grupa i LIMIT",
    goal: "GROUP BY ... ORDER BY ... LIMIT 1.",
    concept: "Aggregates/GROUP BY/HAVING",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_aggfunc.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ miejsce_id: 1, cnt: 2 }],
    solution_sql: "SELECT miejsce_id, COUNT(*) AS cnt FROM wydarzenia WHERE miejsce_id IS NOT NULL GROUP BY miejsce_id ORDER BY cnt DESC LIMIT 1",
    version: 1,
  },
  {
    id: "join-inner-2",
    theme: "polonia",
    title: "Wydarzenia z nazwą miejsca",
    goal: "Tabela miejsca (id, nazwa); wydarzenia.miejsce_id. Pokaż wydarzenia z nazwą miejsca (INNER JOIN).",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", nazwa_miejsca: "Park miejski" },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", nazwa_miejsca: "Dom parafialny" },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", nazwa_miejsca: "Rynek" },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", nazwa_miejsca: "Rynek" },
    ],
    solution_sql: "SELECT w.id, w.nazwa, w.data_wydarzenia, m.nazwa AS nazwa_miejsca FROM wydarzenia w INNER JOIN miejsca m ON w.miejsce_id = m.id",
    version: 1,
  },
  {
    id: "join-left",
    theme: "polonia",
    title: "Wszystkie miejsca i wydarzenia",
    goal: "LEFT JOIN: miejsca po lewej; pokaż miejsca bez wydarzeń też.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Rynek", wydarzenie_id: 3, wydarzenie_nazwa: "Kiermasz świąteczny" },
      { id: 1, nazwa: "Rynek", wydarzenie_id: 4, wydarzenie_nazwa: "Jarmark" },
      { id: 2, nazwa: "Park miejski", wydarzenie_id: 1, wydarzenie_nazwa: "Dożynki" },
      { id: 3, nazwa: "Dom parafialny", wydarzenie_id: 2, wydarzenie_nazwa: "Spotkanie cechu" },
      { id: 4, nazwa: "Sala", wydarzenie_id: null, wydarzenie_nazwa: null },
    ],
    solution_sql: "SELECT m.id, m.nazwa, w.id AS wydarzenie_id, w.nazwa AS wydarzenie_nazwa FROM miejsca m LEFT JOIN wydarzenia w ON w.miejsce_id = m.id",
    version: 1,
  },
  {
    id: "join-where-join",
    theme: "polonia",
    title: "JOIN i WHERE",
    goal: "Wydarzenia w miejscu o nazwie 'Rynek' (JOIN + WHERE).",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT w.id, w.nazwa, w.data_wydarzenia, w.miejsce_id FROM wydarzenia w INNER JOIN miejsca m ON w.miejsce_id = m.id WHERE m.nazwa = 'Rynek'",
    version: 1,
  },
  {
    id: "join-var-58",
    theme: "polonia",
    title: "Wiele JOINów",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", miejsce: "Park miejski" },
      { id: 3, nazwa: "Kiermasz świąteczny", miejsce: "Rynek" },
      { id: 4, nazwa: "Jarmark", miejsce: "Rynek" },
    ],
    solution_sql: "SELECT w.id, w.nazwa, m.nazwa AS miejsce FROM wydarzenia w INNER JOIN miejsca m ON w.miejsce_id = m.id AND m.nazwa IN ('Rynek', 'Park miejski')",
    version: 1,
  },
  {
    id: "join-var-59",
    theme: "polonia",
    title: "Self-join",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ nazwa_a: "Kiermasz świąteczny", nazwa_b: "Jarmark" }],
    solution_sql: "SELECT a.nazwa AS nazwa_a, b.nazwa AS nazwa_b FROM wydarzenia a JOIN wydarzenia b ON a.miejsce_id = b.miejsce_id AND a.id < b.id",
    version: 1,
  },
  {
    id: "join-var-60",
    theme: "polonia",
    title: "RIGHT JOIN",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", miejsce_nazwa: "Park miejski" },
      { id: 2, nazwa: "Spotkanie cechu", miejsce_nazwa: "Dom parafialny" },
      { id: 3, nazwa: "Kiermasz świąteczny", miejsce_nazwa: "Rynek" },
      { id: 4, nazwa: "Jarmark", miejsce_nazwa: "Rynek" },
      { id: 5, nazwa: "Bez miejsca", miejsce_nazwa: null },
    ],
    solution_sql: "SELECT w.id, w.nazwa, m.nazwa AS miejsce_nazwa FROM wydarzenia w LEFT JOIN miejsca m ON w.miejsce_id = m.id",
    version: 1,
  },
  {
    id: "join-var-61",
    theme: "polonia",
    title: "CROSS JOIN",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa_m: "Rynek", nazwa_w: "Dożynki" },
      { nazwa_m: "Rynek", nazwa_w: "Spotkanie cechu" },
      { nazwa_m: "Rynek", nazwa_w: "Kiermasz świąteczny" },
      { nazwa_m: "Rynek", nazwa_w: "Jarmark" },
      { nazwa_m: "Rynek", nazwa_w: "Bez miejsca" },
      { nazwa_m: "Park miejski", nazwa_w: "Dożynki" },
      { nazwa_m: "Park miejski", nazwa_w: "Spotkanie cechu" },
      { nazwa_m: "Park miejski", nazwa_w: "Kiermasz świąteczny" },
      { nazwa_m: "Park miejski", nazwa_w: "Jarmark" },
      { nazwa_m: "Park miejski", nazwa_w: "Bez miejsca" },
      { nazwa_m: "Dom parafialny", nazwa_w: "Dożynki" },
      { nazwa_m: "Dom parafialny", nazwa_w: "Spotkanie cechu" },
      { nazwa_m: "Dom parafialny", nazwa_w: "Kiermasz świąteczny" },
      { nazwa_m: "Dom parafialny", nazwa_w: "Jarmark" },
      { nazwa_m: "Dom parafialny", nazwa_w: "Bez miejsca" },
      { nazwa_m: "Sala", nazwa_w: "Dożynki" },
      { nazwa_m: "Sala", nazwa_w: "Spotkanie cechu" },
      { nazwa_m: "Sala", nazwa_w: "Kiermasz świąteczny" },
      { nazwa_m: "Sala", nazwa_w: "Jarmark" },
      { nazwa_m: "Sala", nazwa_w: "Bez miejsca" },
    ],
    solution_sql: "SELECT m.nazwa AS nazwa_m, w.nazwa AS nazwa_w FROM miejsca m CROSS JOIN wydarzenia w",
    version: 1,
  },
  {
    id: "join-var-62",
    theme: "polonia",
    title: "JOIN z USING",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce_id: 1, id: 3, nazwa: "Kiermasz świąteczny" },
      { miejsce_id: 1, id: 4, nazwa: "Jarmark" },
      { miejsce_id: 2, id: 1, nazwa: "Dożynki" },
      { miejsce_id: 3, id: 2, nazwa: "Spotkanie cechu" },
    ],
    solution_sql: "SELECT w.miejsce_id, w.id, w.nazwa FROM wydarzenia w JOIN (SELECT id AS miejsce_id FROM miejsca) m USING(miejsce_id)",
    version: 1,
  },
  {
    id: "join-var-63",
    theme: "polonia",
    title: "Trzy tabele",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", miejsce: "Park miejski", inne: "Park miejski" },
      { nazwa: "Spotkanie cechu", miejsce: "Dom parafialny", inne: "Dom parafialny" },
      { nazwa: "Kiermasz świąteczny", miejsce: "Rynek", inne: "Rynek" },
      { nazwa: "Jarmark", miejsce: "Rynek", inne: "Rynek" },
    ],
    solution_sql: "SELECT w.nazwa, m1.nazwa AS miejsce, m2.nazwa AS inne FROM wydarzenia w JOIN miejsca m1 ON w.miejsce_id = m1.id JOIN miejsca m2 ON m2.id = m1.id",
    version: 1,
  },
  {
    id: "join-var-64",
    theme: "polonia",
    title: "JOIN i GROUP BY",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Rynek", ile: 2 },
      { nazwa: "Park miejski", ile: 1 },
      { nazwa: "Dom parafialny", ile: 1 },
      { nazwa: "Sala", ile: 0 },
    ],
    solution_sql: "SELECT m.nazwa, COUNT(w.id) AS ile FROM miejsca m LEFT JOIN wydarzenia w ON w.miejsce_id = m.id GROUP BY m.id, m.nazwa",
    version: 1,
  },
  {
    id: "join-var-65",
    theme: "polonia",
    title: "JOIN i ORDER BY",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "czeladnik",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce: "Park miejski" },
      { nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce: "Dom parafialny" },
      { nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce: "Rynek" },
      { nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce: "Rynek" },
    ],
    solution_sql: "SELECT w.nazwa, w.data_wydarzenia, m.nazwa AS miejsce FROM wydarzenia w JOIN miejsca m ON w.miejsce_id = m.id ORDER BY w.data_wydarzenia",
    version: 1,
  },
  {
    id: "join-var-66",
    theme: "polonia",
    title: "NATURAL JOIN",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Rynek", wydarzenie_nazwa: "Kiermasz świąteczny" },
      { id: 1, nazwa: "Rynek", wydarzenie_nazwa: "Jarmark" },
      { id: 2, nazwa: "Park miejski", wydarzenie_nazwa: "Dożynki" },
      { id: 3, nazwa: "Dom parafialny", wydarzenie_nazwa: "Spotkanie cechu" },
    ],
    solution_sql: "SELECT m.id, m.nazwa, w.wydarzenie_nazwa FROM (SELECT id, nazwa FROM miejsca) m NATURAL JOIN (SELECT miejsce_id AS id, nazwa AS wydarzenie_nazwa FROM wydarzenia WHERE miejsce_id IS NOT NULL) w",
    version: 1,
  },
  {
    id: "join-var-67",
    theme: "polonia",
    title: "JOIN w podzapytaniu",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { wydarzenie: "Dożynki", miejsce: "Park miejski" },
      { wydarzenie: "Spotkanie cechu", miejsce: "Dom parafialny" },
      { wydarzenie: "Kiermasz świąteczny", miejsce: "Rynek" },
      { wydarzenie: "Jarmark", miejsce: "Rynek" },
    ],
    solution_sql: "SELECT j.wydarzenie, j.miejsce FROM (SELECT w.nazwa AS wydarzenie, m.nazwa AS miejsce FROM wydarzenia w JOIN miejsca m ON w.miejsce_id = m.id) AS j",
    version: 1,
  },
  {
    id: "join-var-68",
    theme: "polonia",
    title: "LEFT JOIN i NULL",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ nazwa: "Sala" }],
    solution_sql: "SELECT m.nazwa FROM miejsca m LEFT JOIN wydarzenia w ON w.miejsce_id = m.id WHERE w.id IS NULL",
    version: 1,
  },
  {
    id: "join-var-69",
    theme: "polonia",
    title: "FULL OUTER (emulacja)",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Rynek", wid: 3 },
      { id: 1, nazwa: "Rynek", wid: 4 },
      { id: 2, nazwa: "Park miejski", wid: 1 },
      { id: 3, nazwa: "Dom parafialny", wid: 2 },
      { id: 4, nazwa: "Sala", wid: null },
      { id: 1, nazwa: "Rynek", wid: 3 },
      { id: 1, nazwa: "Rynek", wid: 4 },
      { id: 2, nazwa: "Park miejski", wid: 1 },
      { id: 3, nazwa: "Dom parafialny", wid: 2 },
      { id: null, nazwa: null, wid: 5 },
    ],
    solution_sql: "SELECT m.id, m.nazwa, w.id AS wid FROM miejsca m LEFT JOIN wydarzenia w ON w.miejsce_id = m.id UNION ALL SELECT m.id, m.nazwa, w.id FROM wydarzenia w LEFT JOIN miejsca m ON w.miejsce_id = m.id",
    version: 1,
  },
  {
    id: "join-var-70",
    theme: "polonia",
    title: "JOIN po różnych kolumnach",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", miejsce: "Park miejski" },
      { nazwa: "Kiermasz świąteczny", miejsce: "Rynek" },
      { nazwa: "Jarmark", miejsce: "Rynek" },
    ],
    solution_sql: "SELECT w.nazwa, m.nazwa AS miejsce FROM wydarzenia w JOIN miejsca m ON w.miejsce_id = m.id AND m.id IN (1, 2)",
    version: 1,
  },
  {
    id: "join-var-71",
    theme: "polonia",
    title: "JOIN i HAVING",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ nazwa: "Rynek", ile: 2 }],
    solution_sql: "SELECT m.nazwa, COUNT(w.id) AS ile FROM miejsca m LEFT JOIN wydarzenia w ON w.miejsce_id = m.id GROUP BY m.id HAVING COUNT(w.id) >= 2",
    version: 1,
  },
  {
    id: "join-var-72",
    theme: "polonia",
    title: "Złożony JOIN",
    goal: "Zastosuj odpowiedni typ JOIN.",
    concept: "JOINs",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Jarmark", miejsce: "Rynek" },
      { nazwa: "Kiermasz świąteczny", miejsce: "Rynek" },
    ],
    solution_sql: "SELECT w.nazwa, m.nazwa AS miejsce FROM wydarzenia w JOIN miejsca m ON w.miejsce_id = m.id WHERE m.nazwa = 'Rynek' ORDER BY w.data_wydarzenia",
    version: 1,
  },
  {
    id: "subquery-where-in",
    theme: "polonia",
    title: "Lista ID z podzapytania",
    goal: "Pokaż wydarzenia, których id jest w wyniku podzapytania (WHERE id IN (SELECT ...)).",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce_id IN (SELECT id FROM miejsca WHERE nazwa = 'Rynek')",
    version: 1,
  },
  {
    id: "subquery-from",
    theme: "polonia",
    title: "Podzapytanie w FROM",
    goal: "Użyj wyniku podzapytania jako tabeli (FROM (SELECT ...) AS t).",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny" },
      { id: 4, nazwa: "Jarmark" },
    ],
    solution_sql: "SELECT * FROM (SELECT id, nazwa FROM wydarzenia WHERE miejsce_id = 1) AS t",
    version: 1,
  },
  {
    id: "subquery-select",
    theme: "polonia",
    title: "Skalar w SELECT",
    goal: "Dla każdego wiersza pokaż kolumnę + wynik podzapytania (SELECT ..., (SELECT ...)).",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", ile_miejsc: 4 },
      { nazwa: "Spotkanie cechu", ile_miejsc: 4 },
      { nazwa: "Kiermasz świąteczny", ile_miejsc: 4 },
      { nazwa: "Jarmark", ile_miejsc: 4 },
      { nazwa: "Bez miejsca", ile_miejsc: 4 },
    ],
    solution_sql: "SELECT nazwa, (SELECT COUNT(*) FROM miejsca) AS ile_miejsc FROM wydarzenia",
    version: 1,
  },
  {
    id: "subq-var-76",
    theme: "polonia",
    title: "EXISTS",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia w WHERE EXISTS (SELECT 1 FROM miejsca m WHERE m.id = w.miejsce_id AND m.nazwa = 'Rynek')",
    version: 1,
  },
  {
    id: "subq-var-77",
    theme: "polonia",
    title: "NOT EXISTS",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ id: 4, nazwa: "Sala" }],
    solution_sql: "SELECT * FROM miejsca m WHERE NOT EXISTS (SELECT 1 FROM wydarzenia w WHERE w.miejsce_id = m.id)",
    version: 1,
  },
  {
    id: "subq-var-78",
    theme: "polonia",
    title: "Korelacja",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", miejsce: "Park miejski" },
      { nazwa: "Spotkanie cechu", miejsce: "Dom parafialny" },
      { nazwa: "Kiermasz świąteczny", miejsce: "Rynek" },
      { nazwa: "Jarmark", miejsce: "Rynek" },
      { nazwa: "Bez miejsca", miejsce: null },
    ],
    solution_sql: "SELECT w.nazwa, (SELECT m.nazwa FROM miejsca m WHERE m.id = w.miejsce_id) AS miejsce FROM wydarzenia w",
    version: 1,
  },
  {
    id: "subq-var-79",
    theme: "polonia",
    title: "Subquery i JOIN",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", nazwa_m: "Park miejski" },
      { nazwa: "Spotkanie cechu", nazwa_m: "Dom parafialny" },
      { nazwa: "Kiermasz świąteczny", nazwa_m: "Rynek" },
      { nazwa: "Jarmark", nazwa_m: "Rynek" },
    ],
    solution_sql: "SELECT w.nazwa, m.nazwa AS nazwa_m FROM wydarzenia w JOIN (SELECT id, nazwa FROM miejsca) m ON w.miejsce_id = m.id",
    version: 1,
  },
  {
    id: "subq-var-80",
    theme: "polonia",
    title: "IN vs EXISTS",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce_id: 2 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce_id: 3 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce_id IN (SELECT id FROM miejsca)",
    version: 1,
  },
  {
    id: "subq-var-81",
    theme: "polonia",
    title: "Scalar subquery warunek",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce_id = (SELECT id FROM miejsca WHERE nazwa = 'Rynek' LIMIT 1)",
    version: 1,
  },
  {
    id: "subq-var-82",
    theme: "polonia",
    title: "FROM subquery z JOIN",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", nazwa_m: "Park miejski" },
      { id: 2, nazwa: "Spotkanie cechu", nazwa_m: "Dom parafialny" },
      { id: 3, nazwa: "Kiermasz świąteczny", nazwa_m: "Rynek" },
      { id: 4, nazwa: "Jarmark", nazwa_m: "Rynek" },
    ],
    solution_sql: "SELECT w.id, w.nazwa, m.nazwa AS nazwa_m FROM (SELECT * FROM wydarzenia WHERE miejsce_id IS NOT NULL) w JOIN miejsca m ON w.miejsce_id = m.id",
    version: 1,
  },
  {
    id: "subq-var-83",
    theme: "polonia",
    title: "Wielokolumnowe IN",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce_id: 2 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce_id: 3 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE (miejsce_id, strftime('%Y', data_wydarzenia)) IN (SELECT id, '2025' FROM miejsca)",
    version: 1,
  },
  {
    id: "subq-var-84",
    theme: "polonia",
    title: "Subquery w HAVING",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Rynek" },
      { nazwa: "Park miejski" },
      { nazwa: "Dom parafialny" },
    ],
    solution_sql: "SELECT m.nazwa FROM miejsca m LEFT JOIN wydarzenia w ON w.miejsce_id = m.id GROUP BY m.id HAVING COUNT(w.id) > (SELECT 0)",
    version: 1,
  },
  {
    id: "subq-var-85",
    theme: "polonia",
    title: "Subquery w ORDER BY",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce_id: 3 },
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce_id: 2 },
      { id: 5, nazwa: "Bez miejsca", data_wydarzenia: "2025-08-01", miejsce_id: null },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia ORDER BY (SELECT nazwa FROM miejsca m WHERE m.id = wydarzenia.miejsce_id)",
    version: 1,
  },
  {
    id: "subq-var-86",
    theme: "polonia",
    title: "Lateral (emulacja)",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { nazwa: "Dożynki", miejsce: "Park miejski" },
      { nazwa: "Spotkanie cechu", miejsce: "Dom parafialny" },
      { nazwa: "Kiermasz świąteczny", miejsce: "Rynek" },
      { nazwa: "Jarmark", miejsce: "Rynek" },
      { nazwa: "Bez miejsca", miejsce: null },
    ],
    solution_sql: "SELECT w.nazwa, (SELECT m.nazwa FROM miejsca m WHERE m.id = w.miejsce_id) AS miejsce FROM wydarzenia w",
    version: 1,
  },
  {
    id: "subq-var-87",
    theme: "polonia",
    title: "NOT IN i NULL",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [{ id: 4, nazwa: "Sala" }],
    solution_sql: "SELECT * FROM miejsca WHERE id NOT IN (SELECT miejsce_id FROM wydarzenia WHERE miejsce_id IS NOT NULL)",
    version: 1,
  },
  {
    id: "subq-var-88",
    theme: "polonia",
    title: "ANY/ALL (emulacja)",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", miejsce_id: 2 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", miejsce_id: 3 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", miejsce_id: 1 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", miejsce_id: 1 },
    ],
    solution_sql: "SELECT * FROM wydarzenia WHERE miejsce_id >= (SELECT MIN(id) FROM miejsca) AND miejsce_id IS NOT NULL",
    version: 1,
  },
  {
    id: "subq-var-89",
    theme: "polonia",
    title: "Subquery z GROUP BY",
    goal: "Zastosuj podzapytanie.",
    concept: "Subqueries",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/lang_select.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { miejsce_id: 1, cnt: 2, nazwa: "Rynek" },
      { miejsce_id: 2, cnt: 1, nazwa: "Park miejski" },
      { miejsce_id: 3, cnt: 1, nazwa: "Dom parafialny" },
    ],
    solution_sql: "SELECT t.miejsce_id, t.cnt, m.nazwa FROM (SELECT miejsce_id, COUNT(*) AS cnt FROM wydarzenia WHERE miejsce_id IS NOT NULL GROUP BY miejsce_id) t JOIN miejsca m ON m.id = t.miejsce_id",
    version: 1,
  },
  {
    id: "window-row-number",
    theme: "polonia",
    title: "Numer wiersza w grupie",
    goal: "ROW_NUMBER() OVER (PARTITION BY miejsce).",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", miejsce_id: 2, rn: 1 },
      { id: 2, nazwa: "Spotkanie cechu", miejsce_id: 3, rn: 1 },
      { id: 3, nazwa: "Kiermasz świąteczny", miejsce_id: 1, rn: 1 },
      { id: 4, nazwa: "Jarmark", miejsce_id: 1, rn: 2 },
    ],
    solution_sql: "SELECT id, nazwa, miejsce_id, ROW_NUMBER() OVER (PARTITION BY miejsce_id ORDER BY id) AS rn FROM wydarzenia WHERE miejsce_id IS NOT NULL",
    version: 1,
  },
  {
    id: "window-rank",
    theme: "polonia",
    title: "Ranking po dacie",
    goal: "RANK() po dacie (np. najbliższe = 1).",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 5, nazwa: "Bez miejsca", data_wydarzenia: "2025-08-01", rk: 1 },
      { id: 1, nazwa: "Dożynki", data_wydarzenia: "2025-09-14", rk: 2 },
      { id: 2, nazwa: "Spotkanie cechu", data_wydarzenia: "2025-10-01", rk: 3 },
      { id: 4, nazwa: "Jarmark", data_wydarzenia: "2025-11-15", rk: 4 },
      { id: 3, nazwa: "Kiermasz świąteczny", data_wydarzenia: "2025-12-07", rk: 5 },
    ],
    solution_sql: "SELECT id, nazwa, data_wydarzenia, RANK() OVER (ORDER BY data_wydarzenia) AS rk FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-sum-over",
    theme: "polonia",
    title: "Suma narastająca",
    goal: "SUM(...) OVER (ORDER BY ...).",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", suma_narastajaca: 1 },
      { id: 2, nazwa: "Spotkanie cechu", suma_narastajaca: 3 },
      { id: 3, nazwa: "Kiermasz świąteczny", suma_narastajaca: 6 },
      { id: 4, nazwa: "Jarmark", suma_narastajaca: 10 },
      { id: 5, nazwa: "Bez miejsca", suma_narastajaca: 15 },
    ],
    solution_sql: "SELECT id, nazwa, SUM(id) OVER (ORDER BY id) AS suma_narastajaca FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-93",
    theme: "polonia",
    title: "DENSE_RANK",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 5, nazwa: "Bez miejsca", dr: 1 },
      { id: 3, nazwa: "Kiermasz świąteczny", dr: 2 },
      { id: 4, nazwa: "Jarmark", dr: 2 },
      { id: 1, nazwa: "Dożynki", dr: 3 },
      { id: 2, nazwa: "Spotkanie cechu", dr: 4 },
    ],
    solution_sql: "SELECT id, nazwa, DENSE_RANK() OVER (ORDER BY COALESCE(miejsce_id, 0)) AS dr FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-94",
    theme: "polonia",
    title: "LAG/LEAD",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", poprzednia: null },
      { id: 2, nazwa: "Spotkanie cechu", poprzednia: "Dożynki" },
      { id: 3, nazwa: "Kiermasz świąteczny", poprzednia: "Spotkanie cechu" },
      { id: 4, nazwa: "Jarmark", poprzednia: "Kiermasz świąteczny" },
      { id: 5, nazwa: "Bez miejsca", poprzednia: "Jarmark" },
    ],
    solution_sql: "SELECT id, nazwa, LAG(nazwa) OVER (ORDER BY id) AS poprzednia FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-95",
    theme: "polonia",
    title: "PARTITION BY + ORDER BY",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 4, nazwa: "Jarmark", miejsce_id: 1, rn: 1 },
      { id: 3, nazwa: "Kiermasz świąteczny", miejsce_id: 1, rn: 2 },
      { id: 1, nazwa: "Dożynki", miejsce_id: 2, rn: 1 },
      { id: 2, nazwa: "Spotkanie cechu", miejsce_id: 3, rn: 1 },
    ],
    solution_sql: "SELECT id, nazwa, miejsce_id, ROW_NUMBER() OVER (PARTITION BY miejsce_id ORDER BY data_wydarzenia) AS rn FROM wydarzenia WHERE miejsce_id IS NOT NULL ORDER BY miejsce_id, rn",
    version: 1,
  },
  {
    id: "window-var-96",
    theme: "polonia",
    title: "first_value/last_value",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", pierwsza: "Dożynki" },
      { id: 2, nazwa: "Spotkanie cechu", pierwsza: "Dożynki" },
      { id: 3, nazwa: "Kiermasz świąteczny", pierwsza: "Dożynki" },
      { id: 4, nazwa: "Jarmark", pierwsza: "Dożynki" },
      { id: 5, nazwa: "Bez miejsca", pierwsza: "Dożynki" },
    ],
    solution_sql: "SELECT id, nazwa, FIRST_VALUE(nazwa) OVER (ORDER BY id) AS pierwsza FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-97",
    theme: "polonia",
    title: "Frame ROWS",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", suma_2: 1 },
      { id: 2, nazwa: "Spotkanie cechu", suma_2: 3 },
      { id: 3, nazwa: "Kiermasz świąteczny", suma_2: 5 },
      { id: 4, nazwa: "Jarmark", suma_2: 7 },
      { id: 5, nazwa: "Bez miejsca", suma_2: 9 },
    ],
    solution_sql: "SELECT id, nazwa, SUM(id) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS suma_2 FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-98",
    theme: "polonia",
    title: "NTILE",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", grupa: 1 },
      { id: 2, nazwa: "Spotkanie cechu", grupa: 1 },
      { id: 3, nazwa: "Kiermasz świąteczny", grupa: 1 },
      { id: 4, nazwa: "Jarmark", grupa: 2 },
      { id: 5, nazwa: "Bez miejsca", grupa: 2 },
    ],
    solution_sql: "SELECT id, nazwa, NTILE(2) OVER (ORDER BY id) AS grupa FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-99",
    theme: "polonia",
    title: "percent_rank/cume_dist",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", pr: 0 },
      { id: 2, nazwa: "Spotkanie cechu", pr: 0.25 },
      { id: 3, nazwa: "Kiermasz świąteczny", pr: 0.5 },
      { id: 4, nazwa: "Jarmark", pr: 0.75 },
      { id: 5, nazwa: "Bez miejsca", pr: 1 },
    ],
    solution_sql: "SELECT id, nazwa, PERCENT_RANK() OVER (ORDER BY id) AS pr FROM wydarzenia",
    version: 1,
  },
  {
    id: "window-var-100",
    theme: "polonia",
    title: "Wiele okien",
    goal: "Zastosuj funkcję okna.",
    concept: "Window",
    stopien: "mistrz",
    reference: "https://www.sqlite.org/windowfunctions.html",
    schema_ddl: SCHEMA_DDL,
    seed_sql: SEED_SQL,
    expected_result: [
      { id: 1, nazwa: "Dożynki", rn: 1, rk: 2 },
      { id: 2, nazwa: "Spotkanie cechu", rn: 2, rk: 3 },
      { id: 3, nazwa: "Kiermasz świąteczny", rn: 3, rk: 5 },
      { id: 4, nazwa: "Jarmark", rn: 4, rk: 4 },
      { id: 5, nazwa: "Bez miejsca", rn: 5, rk: 1 },
    ],
    solution_sql: "SELECT id, nazwa, ROW_NUMBER() OVER (ORDER BY id) AS rn, RANK() OVER (ORDER BY data_wydarzenia) AS rk FROM wydarzenia",
    version: 1,
  },
];
